-- Bu dosya scripts/generate_seed.py tarafından otomatik üretildi.
-- Elle düzenlemeyin; JSON kaynakları değiştiyse scripti tekrar çalıştırın.
begin;

-- ---- categories ----
insert into public.categories (id, title, subtitle, icon, icon_class, sort_order) values
  ('general-culture', 'Türkçe ve Genel Kültür', 'Dilbilgisi, Tarih, Coğrafya, Yurttaşlık ve Güncel Bilgiler', 'landmark', 'blue', 1),
  ('general-legislation', 'Genel Mevzuat', 'Anayasa, Devlet Memurları ve Kamu Yönetimi Kanunları', 'scale', '', 2),
  ('meb-legislation', 'MEB Mevzuatı', 'Millî Eğitim Bakanlığı Özel Mevzuatı ve Düzenlemeleri', 'schoolbook', 'red', 3)
on conflict (id) do update set title=excluded.title, subtitle=excluded.subtitle, icon=excluded.icon, icon_class=excluded.icon_class, sort_order=excluded.sort_order;

-- ---- topics (kategori ağacı) ----
insert into public.topics (id, category_id, parent_id, type, title, document_number, article_range, article_count, question_count, kadrolar, sort_order, source_file) values
  ('topic-turkce', 'general-culture', NULL, 'topic', 'Türkçe Dilbilgisi ve Anlatım Bozuklukları', NULL, NULL, NULL, 20, '{"memur","sef","sayman","sube-mudur"}', 1, 'sorular/questions-turkce.json'),
  ('topic-inkilap', 'general-culture', NULL, 'topic', 'Atatürk İlkeleri ve İnkılap Tarihi', NULL, NULL, NULL, 20, '{"memur","sef","sayman","sube-mudur"}', 2, 'sorular/questions-inkilap.json'),
  ('topic-cografya', 'general-culture', NULL, 'topic', 'Türkiye Coğrafyası ve Jeopolitiği', NULL, NULL, NULL, 20, '{"memur","sef","sayman","sube-mudur"}', 3, 'sorular/questions-cografya.json'),
  ('topic-yurttaslik', 'general-culture', NULL, 'topic', 'Yurttaşlık Bilgisi ve Temel Hukuk', NULL, NULL, NULL, 20, '{"memur","sef","sayman","sube-mudur"}', 4, 'sorular/questions-yurttaslik.json'),
  ('topic-guncel', 'general-culture', NULL, 'topic', 'Güncel Bilgiler ve Uluslararası Kuruluşlar', NULL, NULL, NULL, 20, '{"memur","sef","sayman","sube-mudur"}', 5, 'sorular/questions-guncel.json'),
  ('law-anayasa', 'general-legislation', NULL, 'document', 'T.C. Anayasası', NULL, NULL, NULL, 20, '{"memur","sef","sayman","sube-mudur"}', 1, 'sorular/questions-anayasa.json'),
  ('law-657', 'general-legislation', NULL, 'document', '657 sayılı Devlet Memurları Kanunu', '657', NULL, NULL, 20, '{"memur","sef","sayman","sube-mudur"}', 2, 'sorular/questions-657.json'),
  ('law-657-section-kapsam-amac-ilkeler', 'general-legislation', 'law-657', 'section', 'Kapsam, Amaç ve Temel İlkeler', NULL, 'Madde 1 – 3', NULL, NULL, '{}', 3, NULL),
  ('law-657-section-istihdam-sekilleri', 'general-legislation', 'law-657', 'section', 'İstihdam Şekilleri', NULL, 'Madde 4 – 5', NULL, NULL, '{}', 4, NULL),
  ('law-657-section-odevler-sorumluluklar', 'general-legislation', 'law-657', 'section', 'Ödevler ve Sorumluluklar', NULL, 'Madde 6 – 16', NULL, NULL, '{}', 5, NULL),
  ('law-657-section-genel-haklar-yasaklar', 'general-legislation', 'law-657', 'section', 'Genel Haklar ve Yasaklar', NULL, 'Madde 17 – 31', NULL, NULL, '{}', 6, NULL),
  ('law-657-section-siniflandirma', 'general-legislation', 'law-657', 'section', 'Sınıflandırma', NULL, 'Madde 32 – 45', NULL, NULL, '{}', 7, NULL),
  ('law-657-section-memurluga-alinma', 'general-legislation', 'law-657', 'section', 'Devlet Memurluğuna Alınma (Usul, Şartlar, Adaylık)', NULL, 'Madde 46 – 57', NULL, NULL, '{}', 8, NULL),
  ('law-657-section-atanma-ilerleme-yer-degistirme', 'general-legislation', 'law-657', 'section', 'Atanma, İlerleme-Yükselme ve Yer Değiştirme', NULL, 'Madde 58 – 93', NULL, NULL, '{}', 9, NULL),
  ('law-657-section-memurlugun-sona-ermesi', 'general-legislation', 'law-657', 'section', 'Memurluğun Sona Ermesi', NULL, 'Madde 94 – 98', NULL, NULL, '{}', 10, NULL),
  ('law-657-section-calisma-saatleri-izinler', 'general-legislation', 'law-657', 'section', 'Çalışma Saatleri ve İzinler', NULL, 'Madde 99 – 108', NULL, NULL, '{}', 11, NULL),
  ('law-657-section-ozluk-dosyasi', 'general-legislation', 'law-657', 'section', 'Özlük Dosyası', NULL, 'Madde 109 – 123', NULL, NULL, '{}', 12, NULL),
  ('law-657-section-disiplin', 'general-legislation', 'law-657', 'section', 'Disiplin Cezaları ve Soruşturma', NULL, 'Madde 124 – 136', NULL, NULL, '{}', 13, NULL),
  ('law-657-section-gorevden-uzaklastirma', 'general-legislation', 'law-657', 'section', 'Görevden Uzaklaştırma', NULL, 'Madde 137 – 145', NULL, NULL, '{}', 14, NULL),
  ('law-657-section-mali-hukumler', 'general-legislation', 'law-657', 'section', 'Mali Hükümler (Aylık ve Ödenekler)', NULL, 'Madde 146 – 186', NULL, NULL, '{}', 15, NULL),
  ('law-657-section-sosyal-haklar-yardimlar', 'general-legislation', 'law-657', 'section', 'Sosyal Haklar ve Yardımlar', NULL, 'Madde 187 – 213', NULL, NULL, '{}', 16, NULL),
  ('law-657-section-memur-yetistirilmesi', 'general-legislation', 'law-657', 'section', 'Devlet Memurlarının Yetiştirilmesi', NULL, 'Madde 214 – 225', NULL, NULL, '{}', 17, NULL),
  ('law-657-section-cesitli-hukumler', 'general-legislation', 'law-657', 'section', 'Çeşitli Hükümler', NULL, 'Madde 226 – 236', NULL, NULL, '{}', 18, NULL),
  ('law-657-section-gecici-ve-son-hukumler', 'general-legislation', 'law-657', 'section', 'Geçici ve Son Hükümler', NULL, 'Ek/Geçici Maddeler, Madde 237 – 239', NULL, NULL, '{}', 19, NULL),
  ('law-4483', 'general-legislation', NULL, 'document', '4483 sayılı Memurlar ve Diğer Kamu Görevlilerinin Yargılanması Hakkında Kanun', NULL, NULL, NULL, 20, '{"memur","sef","sayman","sube-mudur"}', 20, 'sorular/questions-4483.json'),
  ('law-5442', 'general-legislation', NULL, 'document', '5442 sayılı İl İdaresi Kanunu', NULL, NULL, NULL, 20, '{"memur","sef","sayman","sube-mudur"}', 21, 'sorular/questions-5442.json'),
  ('law-4982', 'general-legislation', NULL, 'document', '4982 sayılı Bilgi Edinme Hakkı Kanunu', NULL, NULL, NULL, 20, '{"memur","sef","sayman","sube-mudur"}', 22, 'sorular/questions-4982.json'),
  ('law-3071', 'general-legislation', NULL, 'document', '3071 sayılı Dilekçe Hakkının Kullanılmasına Dair Kanun', NULL, NULL, NULL, 20, '{"memur","sef","sayman","sube-mudur"}', 23, 'sorular/questions-3071.json'),
  ('law-5018', 'general-legislation', NULL, 'document', '5018 sayılı Kamu Mali Yönetimi ve Kontrol Kanunu', NULL, NULL, NULL, 20, '{"sayman","sube-mudur"}', 24, 'sorular/questions-5018.json'),
  ('law-1739', 'meb-legislation', NULL, 'document', '1739 sayılı Milli Eğitim Temel Kanunu', NULL, NULL, 62, 20, '{"memur","sef","sayman","sube-mudur"}', 1, 'sorular/questions-1739.json'),
  ('law-222', 'meb-legislation', NULL, 'document', '222 sayılı İlköğretim ve Eğitim Kanunu', '222', NULL, 91, 61, '{"memur","sef","sayman","sube-mudur"}', 2, 'sorular/questions-222.json'),
  ('law-222-section-genel-esaslar', 'meb-legislation', 'law-222', 'section', 'Genel Esaslar', NULL, 'Madde 1 – 5', NULL, NULL, '{}', 3, NULL),
  ('law-222-section-te-kilat', 'meb-legislation', 'law-222', 'section', 'Teşkilat', NULL, 'Madde 6 – 13', NULL, NULL, '{}', 4, NULL),
  ('law-222-section-i-lde-i-lk-retim-g-revlileri', 'meb-legislation', 'law-222', 'section', 'İlde İlköğretim Görevlileri', NULL, 'Madde 14 – 25', NULL, NULL, '{}', 5, NULL),
  ('law-222-section-i-lk-retim-kurullar', 'meb-legislation', 'law-222', 'section', 'İlköğretim Kurulları', NULL, 'Madde 26', NULL, NULL, '{}', 6, NULL),
  ('law-222-section-a-lma-kapanma-ve-tatiller', 'meb-legislation', 'law-222', 'section', 'Açılma, Kapanma ve Tatiller', NULL, 'Madde 27 – 45', NULL, NULL, '{}', 7, NULL),
  ('law-222-section-kay-t-ve-kabul', 'meb-legislation', 'law-222', 'section', 'Kayıt ve Kabul', NULL, 'Madde 46 – 54', NULL, NULL, '{}', 8, NULL),
  ('law-222-section-okula-devam', 'meb-legislation', 'law-222', 'section', 'Okula Devam', NULL, 'Madde 55 – 61', NULL, NULL, '{}', 9, NULL),
  ('law-222-section-okullar-n-arsa-ve-arazi-i-leri', 'meb-legislation', 'law-222', 'section', 'Okulların Arsa ve Arazi İşleri', NULL, 'Madde 62 – 68', NULL, NULL, '{}', 10, NULL),
  ('law-222-section-okul-yap-m-ve-donat-m', 'meb-legislation', 'law-222', 'section', 'Okul Yapım ve Donatım', NULL, 'Madde 69 – 70', NULL, NULL, '{}', 11, NULL),
  ('law-222-section-gelir-gider-ve-planlama', 'meb-legislation', 'law-222', 'section', 'Gelir, Gider ve Planlama', NULL, 'Madde 71 – 88', NULL, NULL, '{}', 12, NULL),
  ('law-222-section-t-rl-h-k-mler', 'meb-legislation', 'law-222', 'section', 'Türlü Hükümler', NULL, 'Madde 89', NULL, NULL, '{}', 13, NULL),
  ('law-222-section-ek-ge-ici-ve-son-h-k-mler', 'meb-legislation', 'law-222', 'section', 'Ek, Geçici ve Son Hükümler', NULL, 'Ek ve Geçici Maddeler', NULL, NULL, '{}', 14, NULL),
  ('law-cbk1', 'meb-legislation', NULL, 'document', '1 Sayılı Cumhurbaşkanlığı Kararnamesi (MEB Teşkilatı)', NULL, NULL, NULL, 20, '{"memur","sef","sayman","sube-mudur"}', 15, 'sorular/questions-cbk1.json'),
  ('law-5580', 'meb-legislation', NULL, 'document', '5580 sayılı Özel Öğretim Kurumları Kanunu', NULL, NULL, NULL, 20, '{"sayman","sube-mudur"}', 16, 'sorular/questions-5580.json')
on conflict (id) do update set category_id=excluded.category_id, parent_id=excluded.parent_id, type=excluded.type, title=excluded.title, document_number=excluded.document_number, article_range=excluded.article_range, article_count=excluded.article_count, question_count=excluded.question_count, kadrolar=excluded.kadrolar, sort_order=excluded.sort_order, source_file=excluded.source_file;

-- ---- topics (sadece exam-blueprint taxonomy'de geçen ek konular) ----
insert into public.topics (id, category_id, parent_id, type, title, document_number, article_range, article_count, question_count, kadrolar, sort_order, source_file) values
  ('yonetim-insan-iliskileri', 'general-culture', NULL, 'exam_topic', 'Yönetimde İnsan İlişkileri ve İletişim', NULL, NULL, NULL, NULL, '{}', 0, 'sorular/questions-yonetim-insan-iliskileri.json'),
  ('yonetim-liderlik', 'general-culture', NULL, 'exam_topic', 'Yönetim, Liderlik ve Organizasyon', NULL, NULL, NULL, NULL, '{}', 0, 'sorular/questions-yonetim-liderlik.json'),
  ('yonetimde-etik', 'general-culture', NULL, 'exam_topic', 'Yönetimde Etik', NULL, NULL, NULL, NULL, '{}', 0, 'sorular/questions-yonetimde-etik.json'),
  ('4982-kanun', 'general-legislation', NULL, 'exam_topic', '4982 Sayılı Bilgi Edinme Hakkı Kanunu', NULL, NULL, NULL, NULL, '{}', 0, 'sorular/questions-4982-alone.json'),
  ('2886-kanun', 'general-legislation', NULL, 'exam_topic', '2886 Sayılı Devlet İhale Kanunu', NULL, NULL, NULL, NULL, '{}', 0, 'sorular/questions-2886.json'),
  ('4734-kanun', 'general-legislation', NULL, 'exam_topic', '4734 Sayılı Kamu İhale Kanunu', NULL, NULL, NULL, NULL, '{}', 0, 'sorular/questions-4734.json'),
  ('4735-kanun', 'general-legislation', NULL, 'exam_topic', '4735 Sayılı Kamu İhale Sözleşmeleri Kanunu', NULL, NULL, NULL, NULL, '{}', 0, 'sorular/questions-4735.json'),
  ('4688-kanun', 'general-legislation', NULL, 'exam_topic', '4688 Sayılı Kamu Görevlileri Sendikaları ve Toplu Sözleşme Kanunu', NULL, NULL, NULL, NULL, '{}', 0, 'sorular/questions-4688.json'),
  ('652-khk', 'meb-legislation', NULL, 'exam_topic', '652 Sayılı KHK', NULL, NULL, NULL, NULL, '{}', 0, 'sorular/questions-652-khk.json'),
  ('bagli-mevzuat-memur', 'meb-legislation', NULL, 'exam_topic', 'Bağlı Mevzuat (Memur)', NULL, NULL, NULL, NULL, '{}', 0, 'sorular/questions-bagli-mevzuat-memur.json'),
  ('bagli-mevzuat-sef', 'meb-legislation', NULL, 'exam_topic', 'Bağlı Mevzuat (Şef)', NULL, NULL, NULL, NULL, '{}', 0, 'sorular/questions-bagli-mevzuat-sef.json')
on conflict (id) do nothing;

-- ---- card_decks (quiz: taxonomy demo konuları) ----
insert into public.card_decks (id, title, deck_type, category_id, sort_order, source_file) values
  ('turkce', 'Türkçe Dilbilgisi', 'quiz', NULL, 1, 'cards/turkce.json'),
  ('insan-haklari', 'İnsan Hakları ve Demokrasi', 'quiz', NULL, 2, 'cards/insan-haklari.json'),
  ('idare-sistemi', 'Türk İdare Sistemi', 'quiz', NULL, 3, 'cards/idare-sistemi.json'),
  ('protokol', 'Protokol Kuralları', 'quiz', NULL, 4, 'cards/protokol.json'),
  ('ataturk', 'Atatürk İlkeleri ve İnkılap Tarihi', 'quiz', NULL, 5, 'cards/ataturk.json'),
  ('genel-kultur', 'Genel Kültür', 'quiz', NULL, 6, 'cards/genel-kultur.json')
on conflict (id) do update set title=excluded.title, deck_type=excluded.deck_type, sort_order=excluded.sort_order, source_file=excluded.source_file;

-- ---- card_questions ----
insert into public.card_questions (id, deck_id, prompt, options, answer_index, sort_order) values
  ('trk1', 'turkce', 'Aşağıdaki cümlelerin hangisinde yazım yanlışı vardır?', '["Herkez buraya baksın.", "O da bizimle gelecek.", "Bugün hava çok güzel.", "Yarın akşam buluşalım."]'::jsonb, 0, 1),
  ('trk2', 'turkce', 'Hangisi bir noktalama işaretidir?', '["Bağlaç", "Virgül", "Sıfat", "Zamir"]'::jsonb, 1, 2),
  ('trk3', 'turkce', '''Gelmek'' fiilinin şimdiki zaman 1. tekil şahıs çekimi hangisidir?', '["Geldim", "Geliyorum", "Geleceğim", "Gelmeliyim"]'::jsonb, 1, 3),
  ('trk4', 'turkce', 'Hangisinde ünlü düşmesi vardır?', '["Akıl -> Aklı", "Kitap -> Kitabı", "Dolap -> Dolabı", "Ağaç -> Ağacı"]'::jsonb, 0, 4),
  ('trk5', 'turkce', 'Aşağıdakilerden hangisi isimden isim yapan ek almıştır?', '["Gözlük", "Bilgi", "Sevgi", "Yazı"]'::jsonb, 0, 5),
  ('trk6', 'turkce', 'Hangisi eş anlamlı kelimelere örnektir?', '["Siyah - Beyaz", "İyi - Kötü", "Cevap - Yanıt", "Uzun - Kısa"]'::jsonb, 2, 6),
  ('ih1', 'insan-haklari', 'İnsan Hakları Evrensel Bildirgesi hangi yıl kabul edilmiştir?', '["1945", "1948", "1950", "1923"]'::jsonb, 1, 1),
  ('ih2', 'insan-haklari', 'Aşağıdakilerden hangisi temel hak ve özgürlüklerin özelliklerinden biri değildir?', '["Evrenseldir", "Vazgeçilemez", "Devredilemez", "Sınırsızdır"]'::jsonb, 3, 2),
  ('is1', 'idare-sistemi', 'Türkiye''de illerin idaresi hangi esasa dayanır?', '["Yerinden yönetim", "Yetki genişliği", "Özerklik", "Federasyon"]'::jsonb, 1, 1),
  ('is2', 'idare-sistemi', 'Aşağıdakilerden hangisi mahalli idare birimlerinden biridir?', '["Valilik", "Kaymakamlık", "Belediye", "Bakanlık"]'::jsonb, 2, 2),
  ('pr1', 'protokol', 'Resmi yazışmalarda üst makama yazılan yazıların bitiriş ifadesi hangisi olmalıdır?', '["Rica ederim", "Arz ve rica ederim", "Arz ederim", "Bilgilerinize sunarım"]'::jsonb, 2, 1),
  ('pr2', 'protokol', 'Protokolde makam arabasında en onur verici (baş) köşe neresidir?', '["Şoför yanı", "Makam şoförünün arkası", "Makam şoförünün çapraz arkası", "Arka orta"]'::jsonb, 2, 2),
  ('ata1', 'ataturk', 'Türkiye Cumhuriyeti''nin ilk anayasası hangi yıl kabul edilmiştir?', '["1921", "1924", "1961", "1982"]'::jsonb, 1, 1),
  ('ata2', 'ataturk', 'Aşağıdakilerden hangisi Atatürk''ün altı ilkesinden biri değildir?', '["Cumhuriyetçilik", "Halkçılık", "Eşitlikçilik", "Laiklik"]'::jsonb, 2, 2),
  ('ata3', 'ataturk', 'Harf İnkılabı hangi yıl yapılmıştır?', '["1923", "1926", "1928", "1934"]'::jsonb, 2, 3),
  ('ata4', 'ataturk', 'Milli Mücadele''nin askeri safhasını bitiren ateşkes antlaşması hangisidir?', '["Mondros", "Mudanya", "Sevr", "Lozan"]'::jsonb, 1, 4),
  ('gk1', 'genel-kultur', 'Türkiye''nin en yüksek dağı hangisidir?', '["Erciyes", "Süphan", "Ağrı", "Kaçkar"]'::jsonb, 2, 1),
  ('gk2', 'genel-kultur', 'İstiklal Marşı''nın şairi kimdir?', '["Namık Kemal", "Mehmet Akif Ersoy", "Yahya Kemal Beyatlı", "Ziya Gökalp"]'::jsonb, 1, 2),
  ('gk3', 'genel-kultur', 'Dünyanın en uzun nehri hangisidir?', '["Amazon", "Nil", "Yangtze", "Mississippi"]'::jsonb, 1, 3),
  ('gk4', 'genel-kultur', 'Nobel Edebiyat Ödülü''nü kazanan ilk Türk yazar kimdir?', '["Orhan Pamuk", "Yaşar Kemal", "Aziz Nesin", "Elif Şafak"]'::jsonb, 0, 4),
  ('gk5', 'genel-kultur', 'Avrupa Birliği''nin başkenti olarak kabul edilen şehir hangisidir?', '["Paris", "Berlin", "Brüksel", "Strazburg"]'::jsonb, 2, 5)
on conflict (id) do update set deck_id=excluded.deck_id, prompt=excluded.prompt, options=excluded.options, answer_index=excluded.answer_index, sort_order=excluded.sort_order;

-- ---- card_decks (flashcard: kanun kartları, app.js CARD_CATALOGUE) ----
insert into public.card_decks (id, title, deck_type, category_id, sort_order, source_file) values
  ('anayasa', 'T.C. Anayasası', 'flashcard', 'general-legislation', 1, 'cards/anayasa.json'),
  ('657-sayili-kanun', '657 Sayılı Devlet Memurları Kanunu', 'flashcard', 'general-legislation', 2, 'cards/657.json'),
  ('4483-sayili-kanun', '4483 Sayılı Memurlar ve Diğer Kamu Görevlilerinin Yargılanması Hakkında Kanun', 'flashcard', 'general-legislation', 3, 'cards/4483.json'),
  ('5442-sayili-kanun', '5442 Sayılı İl İdaresi Kanunu', 'flashcard', 'general-legislation', 4, 'cards/5442.json'),
  ('4982-sayili-kanun', '4982 Sayılı Bilgi Edinme Hakkı Kanunu', 'flashcard', 'general-legislation', 5, 'cards/4982.json'),
  ('3071-sayili-kanun', '3071 Sayılı Dilekçe Hakkının Kullanılmasına Dair Kanun', 'flashcard', 'general-legislation', 6, 'cards/3071.json')
on conflict (id) do update set title=excluded.title, deck_type=excluded.deck_type, category_id=excluded.category_id, sort_order=excluded.sort_order, source_file=excluded.source_file;

-- ---- flashcards ----
insert into public.flashcards (deck_id, question, answer, sort_order) values
  ('anayasa', '1982 Anayasası hangi tarihte halkoylamasıyla kabul edilmiştir?', '7 Kasım 1982', 1),
  ('anayasa', '1982 Anayasası''nın kanun numarası kaçtır?', '2709', 2),
  ('anayasa', 'Anayasa kaç kısımdan oluşur?', '7 kısım (Başlangıç hariç)', 3),
  ('anayasa', 'Anayasa''nın 2. maddesinde Türkiye Cumhuriyeti nasıl tanımlanır?', 'Toplumun huzuru, millî dayanışma ve adalet anlayışı içinde, insan haklarına saygılı, Atatürk milliyetçiliğine bağlı, demokratik, laik ve sosyal bir hukuk devleti', 4),
  ('anayasa', 'Anayasa''nın 3. maddesine göre Türkiye Devleti''nin bütünlüğü nasıldır?', 'Ülkesi ve milletiyle bölünmez bir bütündür; dili Türkçedir', 5),
  ('anayasa', 'Anayasa''nın 4. maddesi hangi maddeleri değiştirilemez ve değiştirilmesi teklif edilemez kabul eder?', '1, 2 ve 3. maddeler', 6),
  ('anayasa', 'Egemenlik kayıtsız şartsız kime aittir? (Madde 6)', 'Millete', 7),
  ('anayasa', 'Yasama yetkisi kime aittir? (Madde 7)', 'Türk Milleti adına Türkiye Büyük Millet Meclisine', 8),
  ('anayasa', 'Yürütme yetkisi ve görevi kime aittir? (Madde 8)', 'Cumhurbaşkanına', 9),
  ('anayasa', 'Yargı yetkisi kim adına kullanılır? (Madde 9)', 'Türk Milleti adına bağımsız mahkemelerce', 10),
  ('anayasa', 'Madde 10 hangi ilkeyi düzenler?', 'Kanun önünde eşitlik', 11),
  ('anayasa', 'Temel hak ve hürriyetlerin sınırlanması hangi maddede düzenlenir?', 'Madde 13', 12),
  ('anayasa', 'Yaşama hakkı ile kişinin maddi ve manevi varlığı hangi maddede güvence altındadır?', 'Madde 17', 13),
  ('anayasa', 'Zorla çalıştırma yasağı hangi maddede düzenlenir?', 'Madde 18', 14),
  ('anayasa', 'Kişi hürriyeti ve güvenliği hangi maddede düzenlenir?', 'Madde 19', 15),
  ('anayasa', 'Özel hayatın gizliliği hangi maddede düzenlenir?', 'Madde 20', 16),
  ('anayasa', 'Konut dokunulmazlığı hangi maddede düzenlenir?', 'Madde 21', 17),
  ('anayasa', 'Haberleşme hürriyeti hangi maddede düzenlenir?', 'Madde 22', 18),
  ('anayasa', 'Yerleşme ve seyahat hürriyeti hangi maddede düzenlenir?', 'Madde 23', 19),
  ('anayasa', 'Din ve vicdan hürriyeti hangi maddede düzenlenir?', 'Madde 24', 20),
  ('anayasa', 'Düşünce ve kanaat hürriyeti hangi maddede düzenlenir?', 'Madde 25', 21),
  ('anayasa', 'Düşünceyi açıklama ve yayma hürriyeti hangi maddede düzenlenir?', 'Madde 26', 22),
  ('anayasa', 'Bilim ve sanat hürriyeti hangi maddede düzenlenir?', 'Madde 27', 23),
  ('anayasa', 'Basın hürriyeti hangi maddede düzenlenir?', 'Madde 28', 24),
  ('anayasa', 'Toplantı ve gösteri yürüyüşü düzenleme hakkı hangi maddede düzenlenir?', 'Madde 34', 25),
  ('anayasa', 'Mülkiyet hakkı hangi maddede düzenlenir?', 'Madde 35', 26),
  ('anayasa', 'Hak arama hürriyeti hangi maddede düzenlenir?', 'Madde 36', 27),
  ('anayasa', 'Kanuni hâkim güvencesi hangi maddede düzenlenir?', 'Madde 37', 28),
  ('anayasa', 'Suç ve cezalara ilişkin esaslar hangi maddede düzenlenir?', 'Madde 38', 29),
  ('anayasa', 'Dilekçe, bilgi edinme ve kamu denetçisine başvurma hakkı hangi maddede düzenlenir?', 'Madde 74', 30),
  ('anayasa', 'TBMM''nin görev ve yetkileri hangi maddede düzenlenir?', 'Madde 87', 31),
  ('anayasa', 'TBMM kaç milletvekilinden oluşur?', '600', 32),
  ('anayasa', 'Milletvekili seçilme yaşı kaçtır?', '18', 33),
  ('anayasa', 'TBMM ve Cumhurbaşkanlığı seçimleri kaç yılda bir yapılır?', '5 yılda bir', 34),
  ('anayasa', 'Cumhurbaşkanının nitelikleri ve seçimi hangi maddede düzenlenir?', 'Madde 101', 35),
  ('anayasa', 'Cumhurbaşkanının görev ve yetkileri hangi maddede düzenlenir?', 'Madde 104', 36),
  ('anayasa', 'Anayasa Mahkemesi hangi maddede düzenlenir?', 'Madde 146', 37),
  ('anayasa', 'Anayasa Mahkemesi kaç üyeden oluşur?', '15', 38),
  ('anayasa', 'Hâkimler ve Savcılar Kurulu hangi maddede düzenlenir?', 'Madde 159', 39),
  ('anayasa', 'Anayasa değişikliği teklifi TBMM üye tamsayısının kaçta kaçının teklifiyle yapılabilir?', 'En az 1/3''ünün', 40),
  ('657-sayili-kanun', '657 sayılı Devlet Memurları Kanunu hangi tarihte kabul edilmiştir?', '14 Temmuz 1965', 1),
  ('657-sayili-kanun', 'Kanun''un amacı hangi maddede düzenlenir?', 'Madde 1', 2),
  ('657-sayili-kanun', 'Kanun''un temel ilkeleri (sınıflandırma, kariyer, liyakat) hangi maddede sayılır?', 'Madde 3', 3),
  ('657-sayili-kanun', 'Devlet memurluğuna alınacaklarda aranan genel şartlar hangi maddede düzenlenir?', 'Madde 48', 4),
  ('657-sayili-kanun', 'Devlet memuru olabilmek için gereken asgari yaş kaçtır?', '18 yaşını tamamlamış olmak', 5),
  ('657-sayili-kanun', 'Memurların hizmet sınıfları kaç tanedir?', '10 hizmet sınıfı', 6),
  ('657-sayili-kanun', 'Hizmet sınıfları hangi maddede sayılır?', 'Madde 36', 7),
  ('657-sayili-kanun', 'Aday memurluk süresi ne kadardır?', 'En az 1 yıl, en çok 2 yıl', 8),
  ('657-sayili-kanun', 'Aday memurluk hangi maddede düzenlenir?', 'Madde 54', 9),
  ('657-sayili-kanun', 'Memurların haftalık çalışma süresi kaç saattir?', '40 saat', 10),
  ('657-sayili-kanun', 'Çalışma saatleri hangi maddede düzenlenir?', 'Madde 99', 11),
  ('657-sayili-kanun', 'Hizmeti 1-10 yıl arası olan memura yıllık kaç gün izin verilir?', '20 gün', 12),
  ('657-sayili-kanun', 'Hizmeti 10 yıldan fazla olan memura yıllık kaç gün izin verilir?', '30 gün', 13),
  ('657-sayili-kanun', 'Yıllık izin hangi maddede düzenlenir?', 'Madde 102', 14),
  ('657-sayili-kanun', 'Mazeret izni hangi maddede düzenlenir?', 'Madde 104', 15),
  ('657-sayili-kanun', 'Hastalık izni hangi maddede düzenlenir?', 'Madde 105', 16),
  ('657-sayili-kanun', 'Disiplin cezaları kaç türdür?', '5 tür', 17),
  ('657-sayili-kanun', 'Disiplin cezaları hangi maddede sayılır?', 'Madde 125', 18),
  ('657-sayili-kanun', 'En hafif disiplin cezası hangisidir?', 'Uyarma', 19),
  ('657-sayili-kanun', 'En ağır disiplin cezası hangisidir?', 'Devlet memurluğundan çıkarma', 20),
  ('657-sayili-kanun', 'Kademe ilerlemesi hangi maddede düzenlenir?', 'Madde 64', 21),
  ('657-sayili-kanun', 'Derece yükselmesi hangi maddede düzenlenir?', 'Madde 68', 22),
  ('657-sayili-kanun', 'Memurların ödev ve sorumlulukları hangi bölümde düzenlenir?', 'Kanun''un dördüncü kısmında', 23),
  ('657-sayili-kanun', 'Memurların tarafsızlığı ve devlete bağlılığı hangi maddede düzenlenir?', 'Madde 7', 24),
  ('657-sayili-kanun', 'Memurların siyasi partiye üye olması yasak mıdır?', 'Evet, madde 7 uyarınca yasaktır', 25),
  ('657-sayili-kanun', 'Memurların grev yapması hakkında ne öngörülür?', 'Madde 27 uyarınca grev yasağı vardır', 26),
  ('657-sayili-kanun', 'Emeklilik yaş haddi ile ilgili hüküm hangi maddede yer alır?', 'Madde 98 (yaş haddi 65 olarak belirlenmiştir)', 27),
  ('657-sayili-kanun', 'Sicil ve disiplin amirleri kavramı hangi kısımda düzenlenir?', 'Kanun''un disiplin hükümleri bölümünde', 28),
  ('657-sayili-kanun', 'Memurluğun sona erme halleri arasında hangileri sayılır?', 'Çekilme, emeklilik, ölüm, memurluktan çıkarılma gibi haller', 29),
  ('657-sayili-kanun', '657 sayılı Kanun ilk kez hangi Resmi Gazete''de yayımlanmıştır?', '23 Temmuz 1965 tarihli Resmi Gazete''de', 30),
  ('4483-sayili-kanun', '4483 sayılı Kanun hangi tarihte kabul edilmiştir?', '2 Aralık 1999', 1),
  ('4483-sayili-kanun', 'Kanun''un amacı nedir?', 'Memurlar ve diğer kamu görevlilerinin görevleri sebebiyle işledikleri suçlardan dolayı yargılanabilmeleri için izin vermeye yetkili mercileri ve izlenecek usulü düzenlemek', 2),
  ('4483-sayili-kanun', 'Kanun''un amacı hangi maddede düzenlenir?', 'Madde 1', 3),
  ('4483-sayili-kanun', '4483 sayılı Kanun, hangi eski kanunu yürürlükten kaldırmıştır?', '1913 tarihli Memurin Muhakematı Hakkında Kanunu Muvakkat', 4),
  ('4483-sayili-kanun', 'İlçede görevli memurlar hakkında soruşturma izni vermeye yetkili merci kimdir?', 'Kaymakam', 5),
  ('4483-sayili-kanun', 'İlde görevli memurlar hakkında soruşturma izni vermeye yetkili merci kimdir?', 'Vali', 6),
  ('4483-sayili-kanun', 'Bakanlık merkez teşkilatındaki memurlar için izin vermeye yetkili merci kimdir?', 'İlgili bakan', 7),
  ('4483-sayili-kanun', 'Yetkili merci, soruşturma izni konusundaki kararını normal şartlarda kaç gün içinde verir?', 'En geç 30 gün içinde', 8),
  ('4483-sayili-kanun', 'Bakanlıklarda soruşturma izni kararı için öngörülen süre kaç gündür?', 'En geç 60 gün', 9),
  ('4483-sayili-kanun', 'Soruşturma izni verilmesi veya verilmemesi kararına karşı nereye itiraz edilir?', 'Yetkili merciin bağlı bulunduğu bölge idare mahkemesine', 10),
  ('4483-sayili-kanun', 'Soruşturma izni kararına itiraz süresi kaç gündür?', '10 gün', 11),
  ('4483-sayili-kanun', 'Ön inceleme yapmakla görevlendirilen kişi(ler) kimler olabilir?', 'Denetim elemanları veya hakkında inceleme yapılanın üstü konumundaki memurlar', 12),
  ('4483-sayili-kanun', 'Kanun kapsamında memurlar dışında kimler de yer alır?', 'Diğer kamu görevlileri', 13),
  ('4483-sayili-kanun', 'Kanun, hangi tür suçlarla ilgili yargılanma usulünü düzenler?', 'Görevleri sebebiyle işlenen suçlar', 14),
  ('4483-sayili-kanun', 'İzin vermeye yetkili merciin kararı kimlere bildirilir?', 'Hakkında inceleme yapılan memura, varsa şikayetçiye ve Cumhuriyet başsavcılığına', 15),
  ('4483-sayili-kanun', 'Zamanaşımı süreleri işlemeye devam eder mi, yoksa durur mu?', 'Soruşturma izni sürecinde zamanaşımı işlemeye devam eder', 16),
  ('4483-sayili-kanun', 'Kanun kapsamı dışında tutulan bazı suçlar var mıdır?', 'Evet, bazı ağır suçlar (örneğin bazı Ceza Kanunu''nda sayılan suçlar) kanun kapsamı dışında tutulmuştur', 17),
  ('4483-sayili-kanun', '4483 sayılı Kanun kaç maddeden oluşur?', '17 madde (ek ve geçici maddelerle birlikte)', 18),
  ('5442-sayili-kanun', '5442 sayılı İl İdaresi Kanunu hangi tarihte kabul edilmiştir?', '10 Haziran 1949', 1),
  ('5442-sayili-kanun', 'Kanun''un 1. maddesi neyi düzenler?', 'Türkiye''nin merkezi idare kuruluşu bakımından illere, illerin de ilçelere bölünmesini', 2),
  ('5442-sayili-kanun', 'Bir ilin sınırlarının değiştirilmesi nasıl yapılır?', 'Kanunla', 3),
  ('5442-sayili-kanun', 'İl idaresinin başında kim bulunur?', 'Vali', 4),
  ('5442-sayili-kanun', 'Vali''nin hukuki konumu nedir?', 'İlin ve ilin merkez ilçesinin en büyük mülki amiri, hükümetin ve ayrı ayrı her bakanlığın temsilcisi', 5),
  ('5442-sayili-kanun', 'Vali hangi makam tarafından atanır?', 'Cumhurbaşkanı kararıyla', 6),
  ('5442-sayili-kanun', 'İlçe idaresinin başında kim bulunur?', 'Kaymakam', 7),
  ('5442-sayili-kanun', 'Kaymakam kimin emrindedir?', 'Valinin', 8),
  ('5442-sayili-kanun', 'Bucak nedir?', 'İlçelerin, coğrafya durumu ve iş hacmi bakımından ayrıldığı idari birimlerden biri', 9),
  ('5442-sayili-kanun', 'İl idare şube başkanları kimlere denir?', 'İl müdürleri (bakanlıkların illerdeki teşkilat başkanları)', 10),
  ('5442-sayili-kanun', 'İl İdare Kurulu kimlerden oluşur?', 'Vali başkanlığında, hukuk işleri müdürü, defterdar ve il idare şube başkanlarından', 11),
  ('5442-sayili-kanun', 'Vali''nin genel olarak sahip olduğu yetki türü nedir?', 'Hem genel idare hem de mahalli idareler üzerinde idari vesayet yetkisi', 12),
  ('5442-sayili-kanun', 'İl genel idaresi ile ilgili kararlar nasıl alınır?', 'Vali başkanlığında toplanan il idare kurulunca', 13),
  ('5442-sayili-kanun', 'Olağanüstü hallerde valinin yetkileri nasıl değişir?', 'Kanunlarla kendisine verilen ek yetkileri kullanabilir (örn. kamu düzeni, güvenlik tedbirleri)', 14),
  ('5442-sayili-kanun', 'İlçelerin kurulması, kaldırılması veya birleştirilmesi nasıl olur?', 'Kanunla', 15),
  ('5442-sayili-kanun', 'Vali, ilçe kaymakamları üzerinde ne tür bir yetkiye sahiptir?', 'Hiyerarşik amirlik ve denetim yetkisi', 16),
  ('5442-sayili-kanun', 'Kanun''da illerin idaresi hangi ilkeye dayanır?', 'Yetki genişliği ve idarenin bütünlüğü ilkesi', 17),
  ('4982-sayili-kanun', '4982 sayılı Bilgi Edinme Hakkı Kanunu hangi tarihte kabul edilmiştir?', '9 Ekim 2003', 1),
  ('4982-sayili-kanun', 'Kanun''un amacı hangi maddede düzenlenir?', 'Madde 1', 2),
  ('4982-sayili-kanun', 'Kanun''un amacı nedir?', 'Demokratik ve şeffaf yönetimin gereği olan eşitlik, tarafsızlık ve açıklık ilkelerine uygun şekilde bilgi edinme hakkını düzenlemek', 3),
  ('4982-sayili-kanun', 'Bilgi edinme başvurusu ne şekilde yapılabilir?', 'Yazılı olarak veya elektronik ortamda ya da diğer iletişim araçlarıyla', 4),
  ('4982-sayili-kanun', 'Kurum ve kuruluşlar başvurulara normal şartlarda en geç kaç iş günü içinde cevap verir?', 'En geç 15 iş günü', 5),
  ('4982-sayili-kanun', 'Başka bir birimden görüş alınmasını gerektiren başvurularda cevap süresi ne kadardır?', 'En geç 30 iş günü', 6),
  ('4982-sayili-kanun', 'Bilgi edinme başvurusunun reddi hangi hallerde mümkündür?', 'Devlet sırrı, ticari sır, özel hayatın gizliliği gibi istisnalar kapsamına giren bilgiler için', 7),
  ('4982-sayili-kanun', 'Başvurusu reddedilen kişi hangi kurula itiraz edebilir?', 'Bilgi Edinme Değerlendirme Kurulu''na', 8),
  ('4982-sayili-kanun', 'Bilgi Edinme Değerlendirme Kurulu kaç üyeden oluşur?', '9 üye', 9),
  ('4982-sayili-kanun', 'Bilgi edinme hakkı kimlere tanınmıştır?', 'Bilgi edinme hakkı; gerçek ve tüzel kişilere (Türk vatandaşları, Türkiye''de ikamet eden yabancılar ve karşılıklılık ilkesi çerçevesinde yabancı gerçek/tüzel kişiler) tanınmıştır', 10),
  ('4982-sayili-kanun', 'Devlet sırrı niteliğindeki bilgiler kanun kapsamında mıdır?', 'Hayır, istisna kapsamındadır ve verilmez', 11),
  ('4982-sayili-kanun', 'Kurum içi düzenlemeler niteliğindeki bilgi ve belgeler kanun kapsamında mıdır?', 'Kurum içi düzenleme niteliğindeki ve sadece kurum personelini ilgilendiren belgeler istisna kapsamındadır', 12),
  ('4982-sayili-kanun', 'Başvuru dilekçesinde hangi bilgiler bulunmalıdır?', 'Başvuranın adı-soyadı, imzası, oturma yeri veya iş adresi, başvurulan kurum ve istenen bilgi/belgenin açık şekilde belirtilmesi', 13),
  ('4982-sayili-kanun', 'Bilgi edinme başvurusunda bulunmak için herhangi bir gerekçe gösterme zorunluluğu var mıdır?', 'Hayır, gerekçe gösterme zorunluluğu yoktur', 14),
  ('3071-sayili-kanun', '3071 sayılı Kanun hangi tarihte kabul edilmiştir?', '1 Kasım 1984', 1),
  ('3071-sayili-kanun', 'Kanun''un amacı hangi maddede düzenlenir?', 'Madde 1', 2),
  ('3071-sayili-kanun', 'Kanun''un amacı nedir?', 'Türk vatandaşlarının ve Türkiye''de ikamet eden yabancıların kendileriyle veya kamu ile ilgili dilek ve şikayetleri hakkında yetkili makamlara ve TBMM''ye yaptıkları başvuruların incelenmesi ve sonuçlandırılmasında uygulanacak usul ve esasları düzenlemektir', 3),
  ('3071-sayili-kanun', 'Dilekçe hakkı Anayasa''nın hangi maddesine dayanır?', 'Madde 74', 4),
  ('3071-sayili-kanun', 'Dilekçeler kime hitaben yazılabilir?', 'Türkiye Büyük Millet Meclisine veya yetkili makamlara', 5),
  ('3071-sayili-kanun', 'Dilekçede bulunması gereken zorunlu unsurlar nelerdir?', 'Başvuranın adı-soyadı ve imzası ile iş veya ikametgah adresi', 6),
  ('3071-sayili-kanun', 'Yetkili makamlar dilekçeleri en kısa sürede ve en geç kaç gün içinde cevaplandırır?', 'En geç 30 gün içinde', 7),
  ('3071-sayili-kanun', 'Kanun kapsamında hangi başvurular incelenmez?', 'Belli bir konuyu içermeyen, yargı organlarının görevine giren veya yargı kararlarını eleştiren dilekçeler', 8),
  ('3071-sayili-kanun', 'Dilekçe verme hakkı sadece Türk vatandaşlarına mı tanınmıştır?', 'Hayır, Türkiye''de ikamet eden yabancılar da karşılıklılık ilkesi çerçevesinde bu haktan yararlanabilir', 9),
  ('3071-sayili-kanun', 'İmzasız veya adresi olmayan dilekçeler işleme alınır mı?', 'Hayır, incelenmez', 10),
  ('3071-sayili-kanun', 'TBMM''ye yapılan dilekçeler hangi komisyon tarafından incelenir?', 'Dilekçe Komisyonu', 11),
  ('3071-sayili-kanun', 'Kanun kaç maddeden oluşur?', '9 madde', 12);

-- ---- exam_topics ----
insert into public.exam_topics (topic_id, title, category_id, status, question_source, linked_topic_id, card_deck_id, sort_order) values
  ('turkce', 'Türkçe Dilbilgisi', 'general-culture', 'demo', 'cards', NULL, 'turkce', 1),
  ('insan-haklari', 'İnsan Hakları ve Demokrasi', 'general-culture', 'demo', 'cards', NULL, 'insan-haklari', 2),
  ('idare-sistemi', 'Türk İdare Sistemi', 'general-culture', 'demo', 'cards', NULL, 'idare-sistemi', 3),
  ('protokol', 'Protokol Kuralları', 'general-culture', 'demo', 'cards', NULL, 'protokol', 4),
  ('ataturk', 'Atatürk İlkeleri ve İnkılap Tarihi', 'general-culture', 'demo', 'cards', NULL, 'ataturk', 5),
  ('genel-kultur-diger', 'Genel Kültür', 'general-culture', 'demo', 'cards', NULL, 'genel-kultur', 6),
  ('yonetim-insan-iliskileri', 'Yönetimde İnsan İlişkileri ve İletişim', 'general-culture', 'demo', 'sorular', 'yonetim-insan-iliskileri', NULL, 7),
  ('yonetim-liderlik', 'Yönetim, Liderlik ve Organizasyon', 'general-culture', 'demo', 'sorular', 'yonetim-liderlik', NULL, 8),
  ('yonetimde-etik', 'Yönetimde Etik', 'general-culture', 'demo', 'sorular', 'yonetimde-etik', NULL, 9),
  ('anayasa', 'T.C. Anayasası', 'general-legislation', 'demo', 'sorular', 'law-anayasa', NULL, 10),
  ('657-kanun', '657 Sayılı Devlet Memurları Kanunu', 'general-legislation', 'real', 'sorular', 'law-657', NULL, 11),
  ('4483-kanun', '4483 Sayılı Kanun', 'general-legislation', 'demo', 'sorular', 'law-4483', NULL, 12),
  ('5442-kanun', '5442 Sayılı İl İdaresi Kanunu', 'general-legislation', 'demo', 'sorular', 'law-5442', NULL, 13),
  ('4982-kanun', '4982 Sayılı Bilgi Edinme Hakkı Kanunu', 'general-legislation', 'demo', 'sorular', '4982-kanun', NULL, 14),
  ('5018-kanun', '5018 Sayılı Kamu Mali Yönetimi ve Kontrol Kanunu', 'general-legislation', 'demo', 'sorular', 'law-5018', NULL, 15),
  ('2886-kanun', '2886 Sayılı Devlet İhale Kanunu', 'general-legislation', 'demo', 'sorular', '2886-kanun', NULL, 16),
  ('4734-kanun', '4734 Sayılı Kamu İhale Kanunu', 'general-legislation', 'demo', 'sorular', '4734-kanun', NULL, 17),
  ('4735-kanun', '4735 Sayılı Kamu İhale Sözleşmeleri Kanunu', 'general-legislation', 'demo', 'sorular', '4735-kanun', NULL, 18),
  ('4688-kanun', '4688 Sayılı Kamu Görevlileri Sendikaları ve Toplu Sözleşme Kanunu', 'general-legislation', 'demo', 'sorular', '4688-kanun', NULL, 19),
  ('1739-kanun', '1739 Sayılı Milli Eğitim Temel Kanunu', 'meb-legislation', 'real', 'sorular', 'law-1739', NULL, 20),
  ('222-kanun', '222 Sayılı İlköğretim ve Eğitim Kanunu', 'meb-legislation', 'real', 'sorular', 'law-222', NULL, 21),
  ('652-khk', '652 Sayılı KHK', 'meb-legislation', 'demo', 'sorular', '652-khk', NULL, 22),
  ('5580-kanun', '5580 Sayılı Özel Öğretim Kurumları Kanunu', 'meb-legislation', 'demo', 'sorular', 'law-5580', NULL, 23),
  ('bagli-mevzuat-memur', 'Bağlı Mevzuat (Memur)', 'meb-legislation', 'demo', 'sorular', 'bagli-mevzuat-memur', NULL, 24),
  ('bagli-mevzuat-sef', 'Bağlı Mevzuat (Şef)', 'meb-legislation', 'demo', 'sorular', 'bagli-mevzuat-sef', NULL, 25)
on conflict (topic_id) do update set title=excluded.title, category_id=excluded.category_id, status=excluded.status, question_source=excluded.question_source, linked_topic_id=excluded.linked_topic_id, card_deck_id=excluded.card_deck_id, sort_order=excluded.sort_order;

-- ---- questions (ana soru bankası) ----
insert into public.questions (id, topic_id, prompt, options, answer_index, sort_order) values
  ('turkce-01', 'topic-turkce', '''Kalemlik, evimizin en güzel köşesindeydi.'' cümlesinde altı çizili sözcüğün (''kalemlik'') yapım eki hangi tür sözcük türetmiştir?', '["İsimden isim yapım eki ile isim türetilmiştir", "Fiilden isim yapım eki ile isim türetilmiştir", "İsimden fiil yapım eki ile fiil türetilmiştir", "Fiilden fiil yapım eki ile fiil türetilmiştir"]'::jsonb, 0, 1),
  ('turkce-02', 'topic-turkce', 'Aşağıdaki cümlelerin hangisinde büyük ünlü uyumuna aykırı bir sözcük vardır?', '["Kardeşim yarın okula erken gidecek.", "Kitaplığa yeni kitaplar geldi.", "Televizyon programını izledik.", "Bahçedeki güller açmış."]'::jsonb, 2, 2),
  ('turkce-03', 'topic-turkce', '''Kitab-kitabı, ağaç-ağacı'' örneklerinde görülen ses olayı aşağıdakilerden hangisidir?', '["Ünlü daralması", "Ünsüz benzeşmesi", "Ünsüz yumuşaması", "Ünlü düşmesi"]'::jsonb, 2, 3),
  ('turkce-04', 'topic-turkce', '''Öğretmenimiz bize çok değerli bilgiler öğretti ve bizi bilgilendirdi.'' cümlesindeki anlatım bozukluğunun türü nedir?', '["Özne eksikliği", "Anlamca çelişen (gereksiz tekrar/eş anlamlı sözcük) kullanımı", "Yüklem eksikliği", "Zaman uyuşmazlığı"]'::jsonb, 1, 4),
  ('turkce-05', 'topic-turkce', '''Sınava hazırlanan ve başarılı olmak isteyen öğrenciler, düzenli çalışmalı.'' cümlesinde ''öğrenciler'' sözcüğü cümlenin hangi ögesidir?', '["Nesne", "Özne", "Dolaylı tümleç", "Zarf tümleci"]'::jsonb, 1, 5),
  ('turkce-06', 'topic-turkce', 'Aşağıdaki cümlelerin hangisinde noktalama işareti yanlış kullanılmıştır?', '["Ali, sınavdan yüksek not aldı.", "\"Yarın geleceğim\" dedi.", "Kitabı okudum ve; çok beğendim.", "Ankara, Türkiye''nin başkentidir."]'::jsonb, 2, 6),
  ('turkce-07', 'topic-turkce', '''Bu konuda sana katılmıyorum, çünkü sen olayın sadece bir yönünü görüyorsun.'' cümlesinde ''çünkü'' bağlacı cümleye ne tür bir anlam katar?', '["Karşılaştırma", "Sebep-sonuç", "Amaç", "Koşul"]'::jsonb, 1, 7),
  ('turkce-08', 'topic-turkce', '''Gel-mek, koş-mak'' örneklerindeki ''-mek, -mak'' eki fiilin hangi çekim biçimini oluşturur?', '["Fiilimsi (mastar)", "Şahıs eki", "Zaman eki", "Kip eki"]'::jsonb, 0, 8),
  ('turkce-09', 'topic-turkce', 'Aşağıdakilerden hangisi bir isim tamlaması (belirtili isim tamlaması) örneğidir?', '["Yaz tatili", "Öğrencinin kalemi", "Demir kapı", "Güzel çiçek"]'::jsonb, 1, 9),
  ('turkce-10', 'topic-turkce', '''Eve gidip biraz dinlendikten sonra ödevlerimi yapacağım.'' cümlesi yapı bakımından nasıl bir cümledir?', '["Basit cümle", "Birleşik cümle", "Sıralı cümle", "Bağlı cümle"]'::jsonb, 1, 10),
  ('turkce-11', 'topic-turkce', '''Öğretmen, öğrencilere ödevlerini vermeyi unutmadı.'' cümlesindeki ''vermeyi'' sözcüğü hangi fiilimsi türüdür?', '["Sıfat-fiil (partisip)", "Zarf-fiil (gerundium)", "İsim-fiil (mastar)", "Bunların hiçbiri"]'::jsonb, 2, 11),
  ('turkce-12', 'topic-turkce', '''Kapıyı kilitlemeyi unutan hırsız, polislere yakalandı.'' cümlesinde altı çizili söz öbeği (''kilitlemeyi unutan'') cümlenin hangi ögesini nitelemektedir?', '["Yüklemi", "Nesneyi", "Özneyi (''hırsız'')", "Zarf tümlecini"]'::jsonb, 2, 12),
  ('turkce-13', 'topic-turkce', 'Aşağıdaki cümlelerin hangisinde pekiştirme sıfatı kullanılmıştır?', '["Masmavi bir gökyüzü vardı.", "Uzun bir yoldan geldik.", "Kırmızı elbise giydi.", "Yeni bir araba aldı."]'::jsonb, 0, 13),
  ('turkce-14', 'topic-turkce', '''Sokakta oynayan çocuklar, akşam olunca evlerine döndüler.'' cümlesinde zarf tümleci hangisidir?', '["Sokakta oynayan", "Çocuklar", "Akşam olunca", "Evlerine döndüler"]'::jsonb, 2, 14),
  ('turkce-15', 'topic-turkce', '''Kitap okumak, insanı hem eğlendirir hem de bilgilendirir.'' cümlesindeki ''hem...hem de'' bağlacı sözcükler/söz öbekleri arasında nasıl bir ilişki kurar?', '["Karşıtlık", "Eş zamanlılık/birliktelik", "Neden-sonuç", "Amaç-sonuç"]'::jsonb, 1, 15),
  ('turkce-16', 'topic-turkce', 'Aşağıdaki cümlelerin hangisinde bir anlatım bozukluğu yoktur?', '["Bu kitabı okumamı ve incelememi istedi.", "Sınıfın en çalışkan ve tembel öğrencisiydi.", "Öğrenciler soruları hem çözdü hem de bitirdi.", "Kapıyı açtı ve girdi, sonra da kapıyı kapattı."]'::jsonb, 3, 16),
  ('turkce-17', 'topic-turkce', '''Sen de mi bu işe karıştın?'' cümlesindeki ''de'' bağlacının yazımıyla ilgili kural nedir?', '["Bağlaç olan ''de/da'' her zaman ayrı yazılır", "Bağlaç olan ''de/da'' her zaman bitişik yazılır", "Bağlaç ''de/da'' ünlü uyumuna göre bitişik yazılır", "Bağlaç ''de/da'' cümle sonunda yazılmaz"]'::jsonb, 0, 17),
  ('turkce-18', 'topic-turkce', '''Öğretmenin anlattığı konuyu tam olarak anlayamadım.'' cümlesinde ''anlattığı'' sözcüğündeki ''-dığı'' eki hangi fiilimsi grubuna aittir?', '["Zarf-fiil", "Sıfat-fiil", "İsim-fiil", "Bağ-fiil"]'::jsonb, 1, 18),
  ('turkce-19', 'topic-turkce', 'Aşağıdakilerden hangisinde ünlü daralmasına örnek bir kullanım vardır?', '["Diyorum ki (de-i-yorum yerine)", "Geliyorum", "Bakıyorum", "Okuyorum"]'::jsonb, 0, 19),
  ('turkce-20', 'topic-turkce', '''Yağmur yağdığı için maç ertelendi.'' cümlesinde altı çizili yan cümlecik (''yağmur yağdığı için'') temel cümleye ne tür bir anlam katar?', '["Amaç", "Sebep", "Zaman", "Koşul"]'::jsonb, 1, 20),
  ('anayasa-01', 'law-anayasa', '1982 Anayasası''nın kabul tarihi hangisidir?', '["7 Kasım 1982", "9 Eylül 1980", "12 Eylül 1982", "20 Ekim 1981"]'::jsonb, 0, 1),
  ('anayasa-02', 'law-anayasa', 'Anayasa''ya göre Türkiye Devleti''nin şekli nedir?', '["Cumhuriyettir", "Monarşidir", "Federasyondur", "Konfederasyondur"]'::jsonb, 0, 2),
  ('anayasa-03', 'law-anayasa', 'Anayasa''nın ''değiştirilemez ve değiştirilmesi teklif dahi edilemez'' maddeleri hangi maddededir?', '["Madde 1, 2 ve 3", "Madde 4", "Madde 10", "Madde 11"]'::jsonb, 1, 3),
  ('anayasa-04', 'law-anayasa', 'Kanun önünde eşitlik ilkesi Anayasa''nın hangi maddesinde düzenlenir?', '["Madde 5", "Madde 10", "Madde 12", "Madde 90"]'::jsonb, 1, 4),
  ('anayasa-05', 'law-anayasa', 'Yasama yetkisi Anayasa''ya göre kime aittir?', '["Cumhurbaşkanına", "Türk Milleti adına TBMM''ye", "Bakanlar Kuruluna", "Anayasa Mahkemesine"]'::jsonb, 1, 5),
  ('anayasa-06', 'law-anayasa', 'Anayasa Mahkemesi kaç üyeden oluşur?', '["11", "13", "15", "17"]'::jsonb, 2, 6),
  ('anayasa-07', 'law-anayasa', 'Temel hak ve hürriyetlerin sınırlanması hangi maddede düzenlenmiştir?', '["Madde 13", "Madde 14", "Madde 15", "Madde 16"]'::jsonb, 0, 7),
  ('anayasa-08', 'law-anayasa', 'Cumhurbaşkanının görev süresi kaç yıldır?', '["4 yıl", "5 yıl", "6 yıl", "7 yıl"]'::jsonb, 1, 8),
  ('657-01', 'law-657', '657 sayılı Devlet Memurları Kanunu''nun temel ilkeleri hangisinde tam olarak verilmiştir?', '["Eşitlik - Adalet - Tarafsızlık", "Sınıflandırma - Kariyer - Liyakat", "Kıdem - Eğitim - Verimlilik", "Hiyerarşi - Sadakat - Güvence"]'::jsonb, 1, 1),
  ('657-02', 'law-657', 'Devlet memurlarının yaptıkları hizmetler için liyakat ilkesinin esası nedir?', '["Sadece yükseköğrenim mezunu olmak", "Sınıfı içinde en yüksek dereceye kadar yükselme imkanı", "Giriş ve ilerleyişin liyakat sistemine dayandırılması", "Kurum amirinin takdiriyle terfi etmek"]'::jsonb, 2, 2),
  ('657-03', 'law-657', '657 sayılı Kanun''a göre kamu hizmetleri aşağıdaki istihdam şekillerinden hangileri eliyle gördürülür?', '["Memurlar ve İşçiler", "Memurlar, Sözleşmeli Personel ve İşçiler", "Memurlar, Geçici Personel, Sözleşmeli Personel, İşçiler", "Memurlar, Stajyerler ve Taşeronlar"]'::jsonb, 1, 3),
  ('657-04', 'law-657', '657 sayılı Kanun kapsamındaki kurumlar dördüncü maddede sayılan istihdam şekilleri dışında personel çalıştırabilir mi?', '["Kurum amiri onayıyla çalıştırabilir", "Bütçe imkânı varsa çalıştırabilir", "Çalıştıramazlar", "Valilik izniyle çalıştırabilir"]'::jsonb, 2, 4),
  ('657-05', 'law-657', 'Devlet memurlarının Anayasa ve kanunlara bağlılık ilkesi neyi ifade eder?', '["Görev saatinde uyumu", "Sadakat ödevini", "Tarafsız kalma hakkını", "Hiyerarşik düzeni"]'::jsonb, 1, 5),
  ('657-06', 'law-657', 'Devlet memurlarının siyasi partilere üye olmalarına ilişkin hüküm hangisidir?', '["Kurum izniyle serbesttir", "Siyasi partilere üye olamazlar", "Görev dışı saatlerde serbesttir", "Sadece yerel partilere üye olabilirler"]'::jsonb, 1, 6),
  ('657-07', 'law-657', 'Devlet memuru amirinden aldığı emri Anayasa veya kanuna aykırı bulursa ne yapmak zorundadır?', '["Emri derhal yerine getirir", "Emri yerine getirmez ve durumu emri verene bildirir", "Polise haber verir", "İstifa eder"]'::jsonb, 1, 7),
  ('657-08', 'law-657', 'Anayasaya veya kanuna aykırı emrin amir tarafından yazılı olarak ısrar edilmesi halinde memur ne yapar?', '["Yine de yapmaz", "Emri yerine getirir ve sorumluluk emri verene ait olur", "Cevap vermez", "Mahkemeye başvurur"]'::jsonb, 1, 8),
  ('657-09', 'law-657', 'Konusu suç teşkil eden emir hakkında memurun tutumu ne olmalıdır?', '["Yazılı verilirse yapılır", "Hiçbir suretle yerine getirilmez", "Amir sorumluluğu alırsa yapılır", "Kısmen yapılır"]'::jsonb, 1, 9),
  ('657-10', 'law-657', 'Devlet memurlarının ticaret ve diğer kazanç getirici faaliyetlerde bulunma yasağı kapsamında hangisi doğrudur?', '["Anonim şirkette yönetim kurulu üyesi olabilir", "Esnaf veya tüccar sayılacak faaliyetlerde bulunamazlar", "Limited şirket ortağı olamazlar", "Kendi adına dükkan açabilirler"]'::jsonb, 1, 10),
  ('657-11', 'law-657', 'Devlet memurlarının toplu olarak görevden çekilmeleri (grev) yasak mıdır?', '["Serbesttir", "Sendika kararıyla yapılabilir", "Kesinlikle yasaktır", "Yalnızca hafta sonu serbesttir"]'::jsonb, 2, 11),
  ('657-12', 'law-657', 'Aşağıdakilerden hangisi devlet memurlarına tanınan genel haklardan biridir?', '["Siyasete atılma hakkı", "Güvenlik ve emeklilik hakkı", "Grev yapma hakkı", "Ticaret yapma hakkı"]'::jsonb, 1, 12),
  ('657-13', 'law-657', '657 sayılı Kanuna göre disiplin cezaları kaç grupta toplanır?', '["3", "4", "5", "6"]'::jsonb, 2, 13),
  ('657-14', 'law-657', 'Aşağıdakilerden hangisi 657 sayılı Kanunda sayılan disiplin cezalarından biri değildir?', '["Uyarma", "Kınama", "Aylıktan kesme", "Sürgün"]'::jsonb, 3, 14),
  ('657-15', 'law-657', 'Memurun görevinde ve davranışlarında daha dikkatli olması gerektiğinin yazı ile bildirilmesi hangi cezadır?', '["Uyarma", "Kınama", "Aylıktan kesme", "Kademe ilerlemesinin durdurulması"]'::jsonb, 0, 15),
  ('657-16', 'law-657', 'Aylıktan kesme cezasında memurun brüt aylığından ne oranda kesinti yapılır?', '["1/10 - 1/5", "1/30 - 1/8", "1/2 - 1/4", "1/50 - 1/100"]'::jsonb, 1, 16),
  ('657-17', 'law-657', 'Savunması alınmadan devlet memuruna disiplin cezası verilebilir mi?', '["Verilebilir", "Verilemez (En az 7 gün süre verilir)", "Kurum amiri isterse verebilir", "Acil durumlarda verilir"]'::jsonb, 1, 17),
  ('657-18', 'law-657', 'Devlet memurluğundan çıkarma cezasını vermeye yetkili organ hangisidir?', '["Disiplin Amiri", "İl Disiplin Kurulu", "Yüksek Disiplin Kurulu", "Valilik"]'::jsonb, 2, 18),
  ('657-19', 'law-657', 'Disiplin cezalarına karşı idari yargı yolu açık mıdır?', '["Açıktır", "Sadece çıkarma cezasına açıktır", "Kapalıdır", "Cumhurbaşkanı kararına bağlıdır"]'::jsonb, 0, 19),
  ('657-20', 'law-657', 'Adaylık süresi içinde disiplin cezası alan aday memurların durumu ne olur?', '["Adaylıkları uzatılır", "İlişikleri kesilir", "Cezaları ertelenir", "Maaşları düşürülür"]'::jsonb, 1, 20),
  ('4483-kanun-01', 'law-4483', '4483 sayılı Kanun''un temel amacı nedir?', '["Memurların yargılanmasında izin usulünü düzenlemek", "Memurların maaşlarını belirlemek", "Disiplin cezalarını düzenlemek", "Memur atamalarını düzenlemek"]'::jsonb, 0, 1),
  ('4483-kanun-02', 'law-4483', 'İlçede görevli memurlar hakkında soruşturma izni vermeye yetkili merci kimdir?', '["Vali", "Kaymakam", "İçişleri Bakanı", "Cumhurbaşkanı"]'::jsonb, 1, 2),
  ('4483-kanun-03', 'law-4483', 'İlde görevli memurlar hakkında soruşturma izni vermeye yetkili merci kimdir?', '["Vali", "Kaymakam", "Bakan", "Başbakan"]'::jsonb, 0, 3),
  ('4483-kanun-04', 'law-4483', 'Yetkili merci, soruşturma izni konusundaki kararını kaç gün içinde vermek zorundadır?', '["10 gün", "15 gün", "30 gün", "60 gün"]'::jsonb, 2, 4),
  ('4483-kanun-05', 'law-4483', 'Hakkında soruşturma izni verilmeyen memur için itiraz edilebilecek merci neresidir?', '["Danıştay", "Bölge İdare Mahkemesi", "Yargıtay", "Sayıştay"]'::jsonb, 1, 5),
  ('4483-kanun-06', 'law-4483', '4483 sayılı Kanun kapsamında ön inceleme yapmakla görevlendirilen kişi kimdir?', '["Müfettiş veya denetime yetkili kişi", "Herhangi bir memur", "Sendika temsilcisi", "Avukat"]'::jsonb, 0, 6),
  ('5442-kanun-01', 'law-5442', '5442 sayılı Kanun''a göre il idaresinin başı kimdir?', '["Vali", "Belediye Başkanı", "Kaymakam", "İl Genel Meclisi Başkanı"]'::jsonb, 0, 1),
  ('5442-kanun-02', 'law-5442', 'İlçe idaresinin başı kimdir?', '["Vali", "Kaymakam", "Muhtar", "İl Müdürü"]'::jsonb, 1, 2),
  ('5442-kanun-03', 'law-5442', 'Vali, ilde hangi organın temsilcisidir?', '["Sadece İçişleri Bakanlığının", "Devletin ve ayrı ayrı her bakanlığın", "Sadece Cumhurbaşkanının", "Belediyenin"]'::jsonb, 1, 3),
  ('5442-kanun-04', 'law-5442', 'İl idare şube başkanları kime karşı sorumludur?', '["Bakanlıklarına doğrudan", "Valiye", "Kaymakama", "Belediye Başkanına"]'::jsonb, 1, 4),
  ('5442-kanun-05', 'law-5442', 'Kaymakam, ilçesinde hangi sıfatla görev yapar?', '["Hükümetin temsilcisi ve ilçenin en büyük mülki amiri", "Sadece belediye temsilcisi", "İl Genel Meclisi üyesi", "Muhtarların amiri"]'::jsonb, 0, 5),
  ('5442-kanun-06', 'law-5442', 'İl idare kurulu kimlerden oluşur?', '["Vali başkanlığında ilgili il müdürlerinden", "Sadece Vali''den", "Belediye meclisinden", "Kaymakamlardan"]'::jsonb, 0, 6),
  ('4982-01', 'law-4982', '4982 sayılı Bilgi Edinme Hakkı Kanunu''nun amacı nedir?', '["Demokratik ve şeffaf yönetimin gereği olan bilgi edinme hakkını düzenlemek", "Sadece basın mensuplarına bilgi vermek", "Ticari sırları korumak", "Kamu ihalelerini düzenlemek"]'::jsonb, 0, 1),
  ('4982-02', 'law-4982', 'Bilgi edinme başvurularına kurumların yanıt vermesi gereken azami süre nedir?', '["15 iş günü", "30 iş günü", "10 gün", "60 gün"]'::jsonb, 0, 2),
  ('4982-03', 'law-4982', 'Devlet sırrı niteliğindeki bilgiler bilgi edinme hakkı kapsamında mıdır?', '["Evet, tamamen kapsamdadır", "Hayır, kapsam dışıdır", "Sadece mahkeme kararıyla açıklanır", "Sadece basına açıklanır"]'::jsonb, 1, 3),
  ('4982-04', 'law-4982', '4982 sayılı Kanuna göre başvuru hangi organa yapılır?', '["Bilgi Edinme Değerlendirme Kurulu''na veya ilgili kuruma", "Sadece Cumhurbaşkanlığına", "Sadece Sayıştaya", "Sadece Danıştaya"]'::jsonb, 0, 4),
  ('4982-05', 'law-4982', 'Bilgi edinme başvurusunun reddi halinde başvurulacak üst mercii nedir?', '["Bilgi Edinme Değerlendirme Kurulu", "Belediye Meclisi", "İl Genel Meclisi", "Sendika"]'::jsonb, 0, 5),
  ('4982-06', 'law-4982', '4982 sayılı Kanun''a göre hangi bilgi/belge bilgi edinme hakkı kapsamı dışındadır?', '["Kurum içi düzenlemeler niteliğindeki kararlar ile tavsiye, mütalaa ve öneriler", "Kurumun görev alanına giren tüm belgeler", "Kamuoyunu ilgilendiren tüm kararlar", "Bütçe belgeleri"]'::jsonb, 0, 6),
  ('5018-kanun-01', 'law-5018', '5018 sayılı Kanun''un temel amacı nedir?', '["Kamu kaynaklarının etkili, ekonomik ve verimli kullanılmasını sağlamak", "Sadece vergi toplamak", "Sadece maaş ödemelerini düzenlemek", "Sadece ihale usullerini belirlemek"]'::jsonb, 0, 1),
  ('5018-kanun-02', 'law-5018', 'Kanun''a göre bütçe türlerinden biri değildir?', '["Merkezi yönetim bütçesi", "Sosyal güvenlik kurumları bütçesi", "Mahallî idareler bütçesi", "Şirket bilançosu"]'::jsonb, 3, 2),
  ('5018-kanun-03', 'law-5018', 'Harcama yetkilisi kimdir?', '["Bütçeyle ödenek tahsis edilen her bir harcama biriminin en üst yöneticisi", "Sadece Bakan", "Sadece Sayıştay Başkanı", "Sadece Maliye Bakanı"]'::jsonb, 0, 3),
  ('5018-kanun-04', 'law-5018', 'Ön mali kontrol görevi temel olarak kime aittir?', '["Strateji Geliştirme Birimlerine", "Sadece Sayıştaya", "Sadece Bakanlar Kuruluna", "Sadece TBMM''ye"]'::jsonb, 0, 4),
  ('5018-kanun-05', 'law-5018', '5018 sayılı Kanun''a göre stratejik plan hazırlama yükümlülüğü kimlere aittir?', '["Kamu idarelerine", "Sadece belediyelere", "Sadece üniversitelere", "Sadece bakanlıklara"]'::jsonb, 0, 5),
  ('5018-kanun-06', 'law-5018', 'Kamu mali yönetiminin temel ilkelerinden biri değildir?', '["Malî saydamlık", "Hesap verebilirlik", "Stratejik planlama", "Kişisel takdir yetkisi"]'::jsonb, 3, 6),
  ('5018-kanun-07', 'law-5018', 'Bütçe kesin hesap kanunu hangi organca kabul edilir?', '["TBMM", "Bakanlar Kurulu", "Sayıştay", "Cumhurbaşkanlığı"]'::jsonb, 0, 7),
  ('5018-kanun-08', 'law-5018', 'Taşınır mal yönetiminden kim sorumludur?', '["Harcama yetkilisi ve taşınır kayıt yetkilisi", "Sadece Maliye Bakanlığı", "Sadece Sayıştay", "Sadece TBMM"]'::jsonb, 0, 8),
  ('5018-kanun-09', 'law-5018', 'İç denetim faaliyeti hangi amaçla yürütülür?', '["Kurumun risk yönetimi, kontrol ve yönetim süreçlerini değerlendirmek", "Sadece personel sicilini tutmak", "Sadece bütçe hazırlamak", "Sadece ihale açmak"]'::jsonb, 0, 9),
  ('1739-01', 'law-1739', '1739 sayılı Milli Eğitim Temel Kanunu''nun 2. maddesine göre Türk Milli Eğitiminin genel amacı ile ilgili aşağıdakilerden hangisi yanlıştır?', '["Atatürk ilke ve inkılaplarına, Atatürk milliyetçiliğine bağlı yurttaşlar yetiştirmek", "Beden, zihin, ahlak, ruh ve duygu bakımından dengeli ve sağlıklı gelişmiş bir kişilik kazandırmak", "Bireyleri yalnızca belirli bir mesleğe yönlendirip diğer alanlara kapatmak", "İlgi, istidat ve kabiliyetlerini geliştirerek hayata ve üst öğrenime hazırlamak"]'::jsonb, 2, 1),
  ('1739-02', 'law-1739', 'Kanunun 4. maddesinde düzenlenen ''Genellik ve Eşitlik'' ilkesine göre eğitim kurumları kimlere açıktır?', '["Yalnızca Türk vatandaşı erkeklere", "Dil, ırk, cinsiyet, engellilik ve din ayrımı gözetilmeksizin herkese", "Sadece belirli bir gelir düzeyinin üzerindeki ailelerin çocuklarına", "Yalnızca örgün eğitim çağındaki öğrencilere"]'::jsonb, 1, 2),
  ('1739-03', 'law-1739', '''Eğitimde hiçbir kişiye, aileye, zümreye veya sınıfa imtiyaz tanınamaz'' hükmü hangi temel ilke ile ilgilidir?', '["Süreklilik", "Genellik ve eşitlik", "Yöneltme", "Bilimsellik"]'::jsonb, 1, 3),
  ('1739-04', 'law-1739', 'Fertlerin ilgi, istidat ve kabiliyetlerinin eğitim sürecinde belirlenerek yöneltilmesi hangi temel ilkenin konusudur?', '["Yöneltme", "Fırsat ve imkan eşitliği", "Planlılık", "Karma eğitim"]'::jsonb, 0, 4),
  ('1739-05', 'law-1739', 'Milli eğitimde kadın erkek herkese aynı eğitim imkanının sağlanması esas olarak hangi ilkeyle ilgilidir?', '["Fırsat ve imkan eşitliği", "Demokrasi eğitimi", "Süreklilik", "Bilimsellik"]'::jsonb, 0, 5),
  ('1739-06', 'law-1739', '''Fertlerin genel eğitimi belli başlı bir yaş ve devre ile sınırlı olmayıp hayat boyunca devam eder'' ifadesi hangi ilkenin özüdür?', '["Süreklilik", "Genellik ve eşitlik", "Yöneltme", "Karma eğitim"]'::jsonb, 0, 6),
  ('1739-07', 'law-1739', 'Milli eğitim hizmetinin Atatürk inkılap ve ilkelerine ve Anayasada ifadesini bulan Atatürk milliyetçiliğine dayanması hangi ilke kapsamında düzenlenmiştir?', '["Atatürk İnkılap ve İlkeleri, Atatürk Milliyetçiliği", "Laiklik", "Bilimsellik", "Planlılık"]'::jsonb, 0, 7),
  ('1739-08', 'law-1739', 'Eğitim sistemimizde ''demokrasi eğitimi'' ilkesine göre okullarda öncelikle hangisi kazandırılmaya çalışılır?', '["Yalnızca sınav başarısı", "Toplum yaşayışına aktif katılım ve demokratik değerlere bağlılık bilinci", "Yalnızca ezber bilgi aktarımı", "Sadece mesleki beceriler"]'::jsonb, 1, 8),
  ('1739-09', 'law-1739', 'Milli eğitimimizde her derece ve türdeki eğitim müfredat ve ders programlarının, çağdaş bilim ve teknolojinin gereklerine göre sürekli yenileştirilmesi hangi ilkenin gereğidir?', '["Bilimsellik", "Karma eğitim", "Genellik ve eşitlik", "Süreklilik"]'::jsonb, 0, 9),
  ('1739-10', 'law-1739', 'Milli eğitim hizmetinin, hedeflere uygun olarak öğretmen, öğrenci, bina ve donatım gibi unsurları göz önünde bulundurularak planlı bir şekilde yürütülmesi hangi ilkeyle açıklanır?', '["Planlılık", "Yöneltme", "Süreklilik", "Fırsat ve imkan eşitliği"]'::jsonb, 0, 10),
  ('1739-11', 'law-1739', 'Kanunun 15. maddesine göre kız ve erkek çocuklara aynı eğitim kurumlarında birlikte eğitim verilmesi esası aşağıdakilerden hangisidir?', '["Karma eğitim", "Yöneltme", "Demokrasi eğitimi", "Genellik ve eşitlik"]'::jsonb, 0, 11),
  ('1739-12', 'law-1739', '''Okul ile aile işbirliği'' ilkesine göre okulların temel görevlerinden biri nedir?', '["Ailelerin eğitimle ilgili görüş ve isteklerini dikkate almak ve gerekli işbirliğini sağlamak", "Aile ile hiçbir bağlantı kurmamak", "Sadece velilerden mali destek talep etmek", "Öğrenci başarısını sadece okul yönetimine bildirmek"]'::jsonb, 0, 12),
  ('1739-13', 'law-1739', 'Ülkenin her köşesinde ihtiyaç duyulan eğitim ve öğretim faaliyetlerinin devlet imkanları ölçüsünde götürülmesi hangi ilke ile ilgilidir?', '["Her yerde eğitim", "Süreklilik", "Bilimsellik", "Demokrasi eğitimi"]'::jsonb, 0, 13),
  ('1739-14', 'law-1739', '1739 sayılı Kanun''un 18. maddesine göre Türk milli eğitim sistemi kaç ana bölümden oluşur?', '["1", "2", "3", "4"]'::jsonb, 1, 14),
  ('1739-15', 'law-1739', 'Türk milli eğitim sisteminin örgün eğitim bölümü aşağıdaki kurum gruplarından hangisini kapsar?', '["Sadece ilköğretim ve ortaöğretim", "Okul öncesi eğitim, ilköğretim, ortaöğretim ve yükseköğretim kurumları", "Sadece yaygın eğitim kurumları", "Sadece yükseköğretim kurumları"]'::jsonb, 1, 15),
  ('1739-16', 'law-1739', 'Örgün eğitim sistemi dışında kalmış veya belli bir eğitim kademesini tamamlamış kişilere yönelik düzenlenen, örgün eğitimin yanında veya dışında yürütülen eğitim faaliyetlerine ne ad verilir?', '["Yaygın eğitim", "Zorunlu eğitim", "Mesleki eğitim", "Uzaktan eğitim"]'::jsonb, 0, 16),
  ('1739-17', 'law-1739', 'Kanuna göre resmi, özel ve gönüllü her kuruluşun eğitimle ilgili faaliyetleri hangi makamın denetimine tabidir?', '["İçişleri Bakanlığı", "Milli Eğitim Bakanlığı", "Valilik", "Devlet Personel Başkanlığı"]'::jsonb, 1, 17),
  ('1739-18', 'law-1739', '1739 sayılı Kanun''a göre bu kanunda sözü geçen yönetmelikler, kanunun yürürlüğe girmesinden itibaren en geç ne kadar sürede çıkarılır?', '["1 ay içinde", "6 ay içinde", "1 yıl içinde", "2 yıl içinde"]'::jsonb, 2, 18),
  ('1739-19', 'law-1739', '1739 sayılı Milli Eğitim Temel Kanunu kabul tarihi ve niteliği bakımından hangi ifadeyle tanımlanır?', '["14/6/1973 tarihli, Türk eğitim sisteminin temel amaç ve ilkelerini belirleyen çerçeve kanundur", "1961 tarihli, sadece ilköğretimi düzenleyen özel bir kanundur", "1982 tarihli, yalnızca yükseköğretimi düzenleyen bir kanundur", "1997 tarihli, sadece zorunlu eğitim süresini belirleyen bir kanundur"]'::jsonb, 0, 19),
  ('1739-20', 'law-1739', 'Aşağıdakilerden hangisi 1739 sayılı Kanun''un 4-17. maddelerinde sayılan Türk milli eğitiminin temel ilkelerinden biri değildir?', '["Laiklik", "Bilimsellik", "Merkeziyetçilik", "Süreklilik"]'::jsonb, 2, 20),
  ('222-genel-01', 'law-222', '222 sayılı Kanuna göre ilköğretim, kadın ve erkek bütün Türklerin hangi gelişimlerine hizmet eden temel eğitim ve öğretimdir?', '["Bedeni, zihni ve ahlaki gelişmelerine", "Sadece mesleki gelişimlerine", "Yalnızca ekonomik gelişimlerine", "Yükseköğretime hazırlanmalarına"]'::jsonb, 0, 1),
  ('222-genel-02', 'law-222', 'İlköğretimle ilgili aşağıdaki ifadelerden hangisi doğrudur?', '["Öğrenim çağındaki çocuklar için isteğe bağlıdır", "Devlet okullarında ücretlidir", "Öğrenim çağındaki kız ve erkek çocuklar için mecburi, Devlet okullarında parasızdır", "Yalnızca yatılı okullarda verilir"]'::jsonb, 2, 2),
  ('222-genel-03', 'law-222', 'Mecburi ilköğretim çağı hangi yaş grubundaki çocukları kapsar?', '["5-12 yaş", "6-14 yaş", "7-15 yaş", "6-16 yaş"]'::jsonb, 1, 3),
  ('222-genel-04', 'law-222', 'İlkokul birinci sınıfa kayıt için çocuğun ilgili yılın 31 Aralık tarihinde kaç ayını doldurmuş olması esastır?', '["60 ay", "66 ay", "69 ay", "72 ay"]'::jsonb, 3, 4),
  ('222-genel-05', 'law-222', 'Mecburi öğretim çağında olup okul bulunmaması veya sağlık durumu nedeniyle okula devam edemeyen ve özel öğretim gören vatandaşlar için hangi yol öngörülmüştür?', '["Doğrudan öğrenimden muaf tutulmaları", "İmtihanla ve yaşlarına göre uygun sınıf veya mezuniyet imtihanına alınmaları", "Sadece açık öğretime kaydedilmeleri", "Bir sonraki öğretim yılını beklemeleri"]'::jsonb, 1, 5),
  ('222-teskilat-01', 'law-222', 'Aşağıdakilerden hangisi 222 sayılı Kanuna göre isteğe bağlı ilköğretim kurumları arasında yer alır?', '["Okul öncesi eğitim kurumları", "Gezici ilköğretim okulları", "Özel eğitime muhtaç çocuklar için kurulan okullar", "Yatılı ilköğretim okulları"]'::jsonb, 0, 6),
  ('222-teskilat-02', 'law-222', 'Aşağıdakilerden hangisi mecburi ilköğretim kurumlarından biridir?', '["Yalnızca okul öncesi eğitim kurumları", "Özel eğitime muhtaç çocuklar için kurulacak okul ve sınıflar", "Sadece yaz kursları", "Yalnızca yetişkin kursları"]'::jsonb, 1, 7),
  ('222-teskilat-03', 'law-222', '222 sayılı Kanuna göre ilköğretim hangi iki zorunlu okul kademesinden oluşur?', '["Üç yıllık ilkokul ve beş yıllık ortaokul", "Dört yıllık ilkokul ve dört yıllık ortaokul", "Beş yıllık ilkokul ve üç yıllık lise", "İki yıllık okul öncesi ve altı yıllık ilkokul"]'::jsonb, 1, 8),
  ('222-teskilat-04', 'law-222', 'İlkokul ve ortaokulların kuruluşuna ilişkin temel yaklaşım aşağıdakilerden hangisidir?', '["Yalnızca aynı binada kurulabilir", "Sadece köylerde ayrı kurulabilir", "Bağımsız okullar hâlinde kurulmaları esastır", "Yalnızca yatılı olarak kurulabilir"]'::jsonb, 2, 9),
  ('222-teskilat-05', 'law-222', 'Yetiştirici ve tamamlayıcı sınıf ve kursların temel amacı aşağıdakilerden hangisidir?', '["Yükseköğretim kontenjanı belirlemek", "Zamanında öğrenim göremeyen çocuklara kısa yoldan ilköğrenim vermek", "Sadece öğretmenlere hizmet içi eğitim vermek", "Okul binalarının bakımını yürütmek"]'::jsonb, 1, 10),
  ('222-teskilat-06', 'law-222', 'Mecburi ilköğrenim çağındaki engelli çocuklar bakımından kanunun yaklaşımı aşağıdakilerden hangisidir?', '["Özel eğitim ve öğretim görmeleri sağlanır", "Yalnızca evde eğitim alabilirler", "Okula kayıtları ertelenir", "İlköğretim hükümlerinden muaftırlar"]'::jsonb, 0, 11),
  ('222-gorevli-01', 'law-222', 'Aşağıdakilerden hangisi ilköğretim kurumlarında bulunabilecek görevlilerden biri değildir?', '["Rehberlik uzmanı", "Müdür yardımcısı", "Noter", "Gezici öğretmen"]'::jsonb, 2, 12),
  ('222-gorevli-02', 'law-222', 'İlköğretim kurumlarındaki görevlilerin nitelikleri, görev ve yetkileri ile atanma esasları neyle tespit edilir?', '["Yönetmelikle", "Sadece okul aile birliği kararıyla", "Muhtarlık genelgesiyle", "Her okulun kendi iç yönergesiyle"]'::jsonb, 0, 13),
  ('222-gorevli-03', 'law-222', 'Kanuna göre öğretmenler grubu içinde aşağıdakilerden hangisi sayılmıştır?', '["Sadece sınıf öğretmenleri", "Sadece branş öğretmenleri", "Sınıf, branş, okul öncesi, özel eğitim ve gezici öğretmenler ile usta öğreticiler", "Yalnızca rehberlik uzmanları"]'::jsonb, 2, 14),
  ('222-kurul-01', 'law-222', '222 sayılı Kanunda İlköğretim Kurulları başlığı altında yer alan Madde 26''nın güncel hukuki durumu nedir?', '["Yürürlüktedir", "Mülgadır", "Geçici maddedir", "Yönetmeliğe dönüştürülmüştür"]'::jsonb, 1, 15),
  ('222-kurul-02', 'law-222', 'Bir kanun maddesinin mülga olması ne anlama gelir?', '["Maddenin uygulama alanının genişletilmesi", "Maddenin yürürlükten kaldırılması", "Maddenin geçici olarak askıya alınması", "Maddenin yalnızca köylerde uygulanması"]'::jsonb, 1, 16),
  ('222-tatiller-01', 'law-222', 'İlköğretim kurumlarının açılma, kapanma ve öğretime ara verme zamanları hangi usulle düzenlenir?', '["Millî Eğitim Bakanlığınca çıkarılacak yönetmelikle", "Her okulun öğretmenler kurulunca", "İlçe belediye meclisince", "Sadece valilik kararıyla"]'::jsonb, 0, 17),
  ('222-tatiller-02', 'law-222', 'İlköğretim okullarında yaz tatili genel olarak hangi dönem arasındadır?', '["Yarıyıl tatilinden ikinci döneme kadar", "Sınavların bitiminden yeni öğretim yılının başına kadar", "Eylül ayının ilk haftasından sonuna kadar", "Yalnızca Ramazan Bayramı süresince"]'::jsonb, 1, 18),
  ('222-tatiller-03', 'law-222', 'Güncel metinde Madde 45 için hangi ifade doğrudur?', '["Mülgadır", "Yalnızca yaz tatilini düzenler", "Öğretmen atamalarını düzenler", "Okul ücretlerini düzenler"]'::jsonb, 0, 19),
  ('222-kayit-01', 'law-222', 'Her çocuk mecburi ilköğretim çağına girdiği öğretim yılı başında hangi işleme tabi tutulur?', '["İlköğretim okuluna kayıt ve kabule", "Yalnızca seviye tespitine", "Ortaokula nakle", "Açık öğretime kayda"]'::jsonb, 0, 20),
  ('222-kayit-02', 'law-222', 'Mecburi öğrenim çağını bitirdiği öğretim yılı sonuna kadar ilköğretimi bitiremeyen çocuklara en çok kaç öğretim yılı daha devam izni verilebilir?', '["Bir", "İki", "Üç", "Dört"]'::jsonb, 1, 21),
  ('222-kayit-03', 'law-222', 'Bir öğretim yılı hangi tarihler arasındaki süreyi ifade eder?', '["1 Ocak ile 31 Aralık arasını", "Derslerin başlamasından bir hafta önceki tarihten son sınıf sınavlarının bittiği güne kadar olan süreyi", "Sadece iki yarıyıl tatili arasındaki süreyi", "Yalnızca derslerin fiilen işlendiği günleri"]'::jsonb, 1, 22),
  ('222-kayit-04', 'law-222', 'Muhtarlar, mecburi öğrenim çağındaki çocuklara ilişkin çizelgeyi dersler başlamadan en az kaç gün önce hazırlar?', '["7", "10", "15", "30"]'::jsonb, 2, 23),
  ('222-kayit-05', 'law-222', 'Madde 48''de öngörülen çizelge kaç nüsha hazırlanır?', '["Bir", "İki", "Üç", "Dört"]'::jsonb, 2, 24),
  ('222-kayit-06', 'law-222', 'Nüfus cüzdanı olmayan veya nüfus kaydı yapılmamış çocukların yaşlarının tespitinde kim görevlidir?', '["İhtiyar kurulları", "Sadece okul müdürü", "İlçe belediyesi", "Nüfus müdürlüğü"]'::jsonb, 0, 25),
  ('222-kayit-07', 'law-222', 'Birleştirilmiş sınıflar da dahil olmak üzere bir öğretmene düşen öğrenci sayısı en fazla kaç olabilir?', '["30", "35", "40", "45"]'::jsonb, 2, 26),
  ('222-devam-01', 'law-222', 'Özrü nedeniyle okula gidemeyen çocuğun durumu veli, vasi veya aile başkanı tarafından en geç kaç gün içinde okul idaresine bildirilmelidir?', '["Bir gün", "İki gün", "Üç gün", "Beş gün"]'::jsonb, 2, 27),
  ('222-devam-02', 'law-222', 'Çocuğun mecburi ilköğretim kurumuna düzenli devamını sağlama yükümlülüğü öncelikle kime aittir?', '["Veli, vasi veya aile başkanına", "Sadece sınıf öğretmenine", "Yalnızca okul aile birliğine", "Belediyeye"]'::jsonb, 0, 28),
  ('222-devam-03', 'law-222', 'Okula devam etmeyen öğrencilerin devamsızlık sebepleri bakımından okul idaresi ve ilköğretim müfettişlerinin görevi nedir?', '["Sebep araştırması yapıp engelleri gidermeye çalışmak", "Öğrenciyi doğrudan kayıttan silmek", "Sadece veliyi aramak", "Her durumda disiplin cezası vermek"]'::jsonb, 0, 29),
  ('222-devam-04', 'law-222', 'Ailede ölüm, yaralanma, düğün veya tarımsal zorunluluk gibi nedenlerle öğrenciye bir yıl içinde en çok kaç gün izin verilebilir?', '["10 gün", "15 gün", "20 gün", "30 gün"]'::jsonb, 1, 30),
  ('222-devam-05', 'law-222', 'Hastalık, sel, kar, deprem veya yangın gibi sebeplerle okula gelemeyen öğrenci için hangi işlem uygulanır?', '["Devamsız sayılır", "İzinli sayılır", "Kaydı silinir", "Sınava alınmaz"]'::jsonb, 1, 31),
  ('222-devam-06', 'law-222', 'İlköğrenim çağında olup mecburi ilköğretim kurumlarına devam etmeyen çocuklar için aşağıdakilerden hangisi doğrudur?', '["Resmî veya özel iş yerlerinde ücretli ya da ücretsiz çalıştırılamazlar", "Sadece yarı zamanlı çalıştırılabilirler", "Yalnızca aile işletmesinde çalışabilirler", "Okul müdürünün izniyle çalıştırılabilirler"]'::jsonb, 0, 32),
  ('222-devam-07', 'law-222', 'Tebliğe rağmen çocuğunu okula göndermeyen veli veya vasiye, her gün için verilecek idari para cezası tutarı nedir?', '["5 Türk Lirası", "10 Türk Lirası", "15 Türk Lirası", "50 Türk Lirası"]'::jsonb, 2, 33),
  ('222-arsa-01', 'law-222', 'Okul arsası ve uygulama bahçesi için gerekli toprağı seçen komisyona kim başkanlık eder?', '["Bölge ilköğretim müfettişi veya ilçe eğitim müdürü", "Belediye başkanı", "Okul aile birliği başkanı", "İl genel meclisi başkanı"]'::jsonb, 0, 34),
  ('222-arsa-02', 'law-222', 'Okul binalarının yeri belirlenirken aşağıdakilerden hangisi göz önünde bulundurulur?', '["Sağlık, eğitim-öğretim ve ulaşım bakımından elverişlilik", "Yalnızca arsanın piyasa değeri", "Sadece nüfus yoğunluğu", "Yalnızca belediye sınırı"]'::jsonb, 0, 35),
  ('222-arsa-03', 'law-222', 'Okul için gerekli toprak tahsis yoluyla sağlanamadığında gerçek veya tüzel kişilere ait arazi hangi koşulla satın alınabilir?', '["Sahiplerinin rızasıyla", "Sadece mahkeme kararıyla", "Herhangi bir onay aranmadan", "Yalnızca belediye kararıyla"]'::jsonb, 0, 36),
  ('222-arsa-04', 'law-222', 'Her köy okulunun bitişiğinde veya yakınında bulunacak uygulama bahçesi kaç dekardan az ve çok olamaz?', '["1-5 dekar", "2-10 dekar", "5-15 dekar", "10-20 dekar"]'::jsonb, 1, 37),
  ('222-arsa-05', 'law-222', 'Okullar için tahsis, satın alma veya kamulaştırma yoluyla sağlanan toprak ve tesisler kural olarak kimin adına tapuya tescil edilir?', '["Bulundukları yere göre köy veya özel idareler adına", "Yalnızca Millî Eğitim Bakanlığı adına", "Okul müdürü adına", "Her durumda Hazine adına"]'::jsonb, 0, 38),
  ('222-arsa-06', 'law-222', 'Okulların uygulama bahçesinde hangi dersin uygulaması yapılır?', '["Tarım dersleri", "Müzik dersleri", "Yabancı dil dersleri", "Beden eğitimi dersleri"]'::jsonb, 0, 39),
  ('222-yapim-01', 'law-222', 'Köy veya kasaba içinden okul ihtiyaçları için sağlanacak taş, kum ve kireç gibi yapı gereçlerinden hangi mali yük alınmaz?', '["Hiçbir resim", "Yalnızca gelir vergisi", "Yalnızca damga vergisi", "Yalnızca KDV"]'::jsonb, 0, 40),
  ('222-yapim-02', 'law-222', 'Okul yapımı için gerekli kereste ihtiyacı hangi kurum tarafından en iyi şartlarla ve öncelikle karşılanır?', '["Tarım Bakanlığı Orman Genel Müdürlüğü", "İlçe belediyesi", "Okul aile birliği", "Tapu müdürlüğü"]'::jsonb, 0, 41),
  ('222-yapim-03', 'law-222', 'Devlet İktisadi Teşekküllerinde üretilen yapı malzemeleri, ilgili makamların istemi üzerine nasıl verilir?', '["Diğer isteklere tercihan ve bedeli karşılığında", "Ücretsiz ve önceliksiz", "Yalnızca ihale yoluyla", "Sadece belediyelere"]'::jsonb, 0, 42),
  ('222-yapim-04', 'law-222', 'Okul yapımı ve donatımı işlerinde yurttaşların yapacağı ayni yardımlar ile nakdi yardımlar için hangi işlem yapılır?', '["Kabul edilir ve değerlendirilir", "Kesinlikle reddedilir", "Sadece nakdi yardımlar kabul edilir", "Yalnızca belediye kararıyla kabul edilir"]'::jsonb, 0, 43),
  ('222-yapim-05', 'law-222', 'Güncel 222 sayılı Kanun metninde Madde 69 için hangi ifade doğrudur?', '["Mülgadır", "İlköğretim haftasını düzenler", "Kayıt süresini düzenler", "Öğrenci devamsızlık iznini düzenler"]'::jsonb, 0, 44),
  ('222-gelir-01', 'law-222', 'İlköğretim için Devlet bütçesinden yapılacak yardım, Devlet gelirlerinin en az yüzde kaçı olmalıdır?', '["Yüzde 1", "Yüzde 2", "Yüzde 3", "Yüzde 5"]'::jsonb, 2, 45),
  ('222-gelir-02', 'law-222', 'Özel idare bütçelerine ilköğretim için yıllık gelirlerinin en az yüzde kaçı oranında ödenek konulması öngörülür?', '["Yüzde 10", "Yüzde 15", "Yüzde 20", "Yüzde 25"]'::jsonb, 2, 46),
  ('222-gelir-03', 'law-222', 'Köy bütçelerine, köy okullarına gelir sağlamak üzere genel gelirlerinin en az yüzde kaçı oranında ödenek konulması öngörülmüştür?', '["Yüzde 5", "Yüzde 10", "Yüzde 15", "Yüzde 20"]'::jsonb, 1, 47),
  ('222-gelir-04', 'law-222', 'İlköğretime ayrılan gelir ve ödenekler, kanunda gösterilen giderler dışında başka bir yere sarf edilebilir mi?', '["Evet, okul müdürünün onayıyla", "Evet, valilik kararıyla", "Hayır, başka fasıllara da nakledilemez", "Sadece yaz tatilinde edilebilir"]'::jsonb, 2, 48),
  ('222-gelir-05', 'law-222', 'Millî Eğitim Bakanlığı, köy, kasaba ve şehir ilköğretim okulları yapımı hakkında her yıl bütçe kanununa nasıl bir plan ekler?', '["Bir yıllık genel plan", "Üçer yıllık tafsilatlı plan", "On yıllık mali plan", "Sadece il bazlı liste"]'::jsonb, 1, 49),
  ('222-gelir-06', 'law-222', 'İlköğretimin gelirleri ve belirli giderleri, personel masrafları hariç, hangi mali yükümlülüklerden muaftır?', '["Her türlü resim ve vergiden", "Sadece emlak vergisinden", "Sadece motorlu taşıtlar vergisinden", "Hiçbir mali yükümlülükten"]'::jsonb, 0, 50),
  ('222-gelir-07', 'law-222', 'Belirli okul yapım, donatım ve planlama işleri için Millî Eğitim veya Bayındırlık Bakanlıkları en çok kaç yıla kadar gelecek yıllara geçici yüklenmeye girebilir?', '["Bir yıl", "İki yıl", "Üç yıl", "Beş yıl"]'::jsonb, 2, 51),
  ('222-turlu-01', 'law-222', 'Köylerde bu kanunla ilgili çeşitli hizmetler hangi kanunla mecburi sayılan işlerdendir?', '["Köy Kanunu", "Belediye Kanunu", "İl İdaresi Kanunu", "Devlet Memurları Kanunu"]'::jsonb, 0, 52),
  ('222-turlu-02', 'law-222', 'Mecburi ilköğretim kurumlarına kayıt olacak veya devam eden öğrencilere verilecek belgeler bakımından hangi ifade doğrudur?', '["Damga Resmine tabi değildir", "Sadece noter onayıyla geçerlidir", "Her belge için harç alınır", "Yalnızca e-belge düzenlenebilir"]'::jsonb, 0, 53),
  ('222-turlu-03', 'law-222', 'Köylerde bulunan öğretmen konutları öğretmenlere nasıl tahsis edilir?', '["Parasız olarak", "Rayicin yarısı bedelle", "Sadece lojman sırası gelince", "Yalnızca yaz aylarında"]'::jsonb, 0, 54),
  ('222-turlu-04', 'law-222', 'Madde 89''un düzenleme alanı aşağıdakilerden hangisidir?', '["Bazı önceki kanun hükümlerinin yürürlükten kaldırılması", "Öğretmen izinleri", "Okul kayıt ücretleri", "Ders yılı süresi"]'::jsonb, 0, 55),
  ('222-ek-01', 'law-222', '222 sayılı Kanunda geçen ilköğretim müdürü deyimi hangi deyimle değiştirilmiştir?', '["İlçe eğitim müdürü", "İl millî eğitim müdürü", "Okul müdürü", "Eğitim denetmeni"]'::jsonb, 0, 56),
  ('222-ek-02', 'law-222', '222 sayılı Kanunda geçen öğretmenevi deyimi hangi deyimle değiştirilmiştir?', '["Öğretmen lojmanı", "Öğretmen odası", "Eğitim merkezi", "Hizmet binası"]'::jsonb, 0, 57),
  ('222-ek-03', 'law-222', 'Öğretmen bulunmaması hâlinde geçici öğretmen olarak atanabilecekler için aranan alt yaş sınırı nedir?', '["16", "17", "18", "21"]'::jsonb, 2, 58),
  ('222-ek-04', 'law-222', 'Millî Eğitim Bakanlığı, Kanunun yürürlüğe girmesinden itibaren mecburi öğrenim çağındaki öğrencileri tamamen okula kavuşturmak için en geç kaç yıl içinde gerekli hazırlıkları tamamlamakla yükümlü tutulmuştur?', '["5 yıl", "8 yıl", "10 yıl", "15 yıl"]'::jsonb, 2, 59),
  ('222-ek-05', 'law-222', 'Kanunun mali hükümleri hangi tarihte yürürlüğe girer?', '["1 Ocak 1961", "1 Mart 1961", "28 Şubat 1961", "12 Ocak 1961"]'::jsonb, 1, 60),
  ('222-ek-06', 'law-222', '222 sayılı Kanunu yürütme görevi kime verilmiştir?', '["Bakanlar Kuruluna", "Millî Eğitim Bakanına", "TBMM Başkanlığına", "Danıştaya"]'::jsonb, 0, 61),
  ('5580-kanun-01', 'law-5580', '5580 sayılı Kanun neyi düzenler?', '["Özel okul, kurs ve öğretim kurumlarının açılış/işleyiş esaslarını", "Sadece devlet okullarını", "Sadece üniversiteleri", "Sadece meslek odalarını"]'::jsonb, 0, 1),
  ('5580-kanun-02', 'law-5580', 'Özel öğretim kurumu açma izni kim tarafından verilir?', '["Millî Eğitim Bakanlığı (il/ilçe müdürlükleri aracılığıyla)", "Ticaret Odası", "Belediye Meclisi", "Maliye Bakanlığı"]'::jsonb, 0, 2),
  ('5580-kanun-03', 'law-5580', 'Özel öğretim kurumlarının denetimini kim yapar?', '["Millî Eğitim Bakanlığı", "Ticaret Bakanlığı", "Belediye", "Sayıştay"]'::jsonb, 0, 3),
  ('5580-kanun-04', 'law-5580', 'Kanun''a göre özel okullardaki eğitim-öğretim ücretleri nasıl belirlenir?', '["Kanun ve ilgili mevzuat çerçevesinde kurum tarafından belirlenip ilan edilir", "Serbestçe, hiçbir kurala tabi değildir", "Sadece Bakanlar Kurulu belirler", "Sadece belediye belirler"]'::jsonb, 0, 4),
  ('5580-kanun-05', 'law-5580', 'Özel öğretim kurumlarında görev yapacak öğretmenlerde aranan temel şart nedir?', '["İlgili alanda öğretmenlik formasyonu/atama şartlarını taşımak", "Hiçbir şart aranmaz", "Sadece tecrübe yeterlidir", "Sadece yabancı dil bilmek yeterlidir"]'::jsonb, 0, 5),
  ('yonetim-insan-iliskileri-01', 'yonetim-insan-iliskileri', 'Etkili iletişimde ''empati'' neyi ifade eder?', '["Karşıdaki kişinin duygu ve bakış açısını anlayabilme becerisini", "Sadece nazik konuşmayı", "Sadece dinlemeyi", "Sadece göz teması kurmayı"]'::jsonb, 0, 1),
  ('yonetim-insan-iliskileri-02', 'yonetim-insan-iliskileri', 'Örgüt içi iletişim türlerinden ''yatay iletişim'' neyi ifade eder?', '["Aynı hiyerarşik düzeydeki birimler/kişiler arasındaki iletişimi", "Üstten asta iletişimi", "Asttan üste iletişimi", "Kurum dışı iletişimi"]'::jsonb, 0, 2),
  ('yonetim-insan-iliskileri-03', 'yonetim-insan-iliskileri', 'Geri bildirim (feedback) yönetimde neden önemlidir?', '["İletişimin etkinliğini ve performansın gelişimini sağladığı için", "Sadece resmi yazışma gereği olduğu için", "Önemi yoktur", "Sadece disiplin cezası vermek için"]'::jsonb, 0, 3),
  ('yonetim-insan-iliskileri-04', 'yonetim-insan-iliskileri', 'Çatışma yönetiminde ''işbirlikçi (uzlaşmacı)'' yaklaşım neyi hedefler?', '["Her iki tarafın da ihtiyaçlarını karşılayan ortak çözüm bulmayı", "Bir tarafın tamamen kazanmasını", "Sorunu görmezden gelmeyi", "Otoriter kararla sonlandırmayı"]'::jsonb, 0, 4),
  ('yonetim-insan-iliskileri-05', 'yonetim-insan-iliskileri', 'Aktif dinleme becerisinin temel unsuru nedir?', '["Karşı tarafı yargılamadan, dikkatle ve anlamaya çalışarak dinlemek", "Sadece susmak", "Sadece not almak", "Sadece onaylamak"]'::jsonb, 0, 5),
  ('yonetim-liderlik-01', 'yonetim-liderlik', 'Klasik yönetim yaklaşımının öncülerinden biri kimdir?', '["Henri Fayol", "Abraham Maslow", "Douglas McGregor", "Peter Drucker"]'::jsonb, 0, 1),
  ('yonetim-liderlik-02', 'yonetim-liderlik', '''Dönüşümcü liderlik'' yaklaşımının temel özelliği nedir?', '["Vizyon ile astları motive edip değişimi yönetmek", "Sadece kurallara sıkı sıkıya bağlı kalmak", "Sadece ödül-ceza sistemini kullanmak", "Karar almaktan kaçınmak"]'::jsonb, 0, 2),
  ('yonetim-liderlik-03', 'yonetim-liderlik', 'Yönetim fonksiyonlarından biri değildir?', '["Planlama", "Örgütleme", "Yöneltme (yürütme)", "Kişisel çıkar gözetme"]'::jsonb, 3, 3),
  ('yonetim-liderlik-04', 'yonetim-liderlik', 'Organizasyon şemasında ''emir-komuta birliği'' ilkesi neyi ifade eder?', '["Bir astın sadece bir üstten emir alması gerektiğini", "Herkesin herkese emir verebileceğini", "Astların üst olmadan karar alabileceğini", "Emir zincirinin önemsiz olduğunu"]'::jsonb, 0, 4),
  ('yonetim-liderlik-05', 'yonetim-liderlik', 'Maslow''un ihtiyaçlar hiyerarşisinde en üst düzey ihtiyaç hangisidir?', '["Kendini gerçekleştirme", "Fizyolojik ihtiyaçlar", "Güvenlik ihtiyacı", "Ait olma ihtiyacı"]'::jsonb, 0, 5),
  ('yonetimde-etik-01', 'yonetimde-etik', 'Kamu yönetiminde etik davranış ilkelerinin temel amacı nedir?', '["Kamu görevinin tarafsız, dürüst ve hesap verebilir şekilde yürütülmesini sağlamak", "Sadece kişisel çıkarı korumak", "Sadece disiplin cezası vermek", "Sadece bürokrasiyi artırmak"]'::jsonb, 0, 1),
  ('yonetimde-etik-02', 'yonetimde-etik', '''Şeffaflık'' ilkesi kamu yönetiminde neyi ifade eder?', '["Kamu işlemlerinin açık ve denetlenebilir olmasını", "Bilgilerin gizli tutulmasını", "Sadece üst yönetime bilgi verilmesini", "Hiçbir kurala bağlı olmamayı"]'::jsonb, 0, 2),
  ('yonetimde-etik-03', 'yonetimde-etik', 'Kamu görevlisinin ''çıkar çatışmasından kaçınma'' yükümlülüğü ne anlama gelir?', '["Kişisel çıkarını kamu görevinin gerekleriyle çatıştırmamasını", "Sadece maaşını beyan etmesini", "Sadece izin almasını", "Hiçbir anlamı yoktur"]'::jsonb, 0, 3),
  ('4982-kanun-01', '4982-kanun', '4982 sayılı Kanun''un amacı nedir?', '["Demokratik ve şeffaf yönetimin gereği olan bilgi edinme hakkını düzenlemek", "Sadece basın mensuplarına bilgi vermek", "Ticari sırları korumak", "Kamu ihalelerini düzenlemek"]'::jsonb, 0, 1),
  ('4982-kanun-02', '4982-kanun', 'Bilgi edinme başvurularına kurumların yanıt vermesi gereken azami süre nedir?', '["15 iş günü", "30 iş günü", "10 gün", "60 gün"]'::jsonb, 0, 2),
  ('4982-kanun-03', '4982-kanun', 'Devlet sırrı niteliğindeki bilgiler bilgi edinme hakkı kapsamında mıdır?', '["Evet, tamamen kapsamdadır", "Hayır, kapsam dışıdır", "Sadece mahkeme kararıyla açıklanır", "Sadece basına açıklanır"]'::jsonb, 1, 3),
  ('4982-kanun-04', '4982-kanun', '4982 sayılı Kanuna göre başvuru hangi organa yapılır?', '["Bilgi Edinme Değerlendirme Kurulu''na veya ilgili kuruma", "Sadece Cumhurbaşkanlığına", "Sadece Sayıştaya", "Sadece Danıştaya"]'::jsonb, 0, 4),
  ('4982-kanun-05', '4982-kanun', 'Bilgi edinme başvurusunun reddi halinde başvurulacak üst mercii nedir?', '["Bilgi Edinme Değerlendirme Kurulu", "Belediye Meclisi", "İl Genel Meclisi", "Sendika"]'::jsonb, 0, 5),
  ('2886-kanun-01', '2886-kanun', '2886 sayılı Kanun temel olarak neyi düzenler?', '["Devlete ait taşınır/taşınmaz malların satım, kira, yapım gibi ihale usullerini", "Sadece personel alımını", "Sadece bütçe hazırlığını", "Sadece vergi tahsilatını"]'::jsonb, 0, 1),
  ('2886-kanun-02', '2886-kanun', 'Kanun''a göre ihale usullerinden biri değildir?', '["Kapalı teklif usulü", "Açık teklif usulü", "Pazarlık usulü", "Doğrudan atama usulü"]'::jsonb, 3, 2),
  ('2886-kanun-03', '2886-kanun', 'İhale komisyonu en az kaç kişiden oluşur?', '["3 kişi", "5 kişi", "7 kişi", "2 kişi"]'::jsonb, 0, 3),
  ('2886-kanun-04', '2886-kanun', 'Geçici teminat oranı ihale bedelinin genel olarak yüzde kaçıdır?', '["%3", "%1", "%10", "%25"]'::jsonb, 0, 4),
  ('2886-kanun-05', '2886-kanun', 'İhaleye katılamayacaklar arasında kimler sayılmaz?', '["İhaleyi yapan idarenin ihale yetkilisi kişiler", "Herkes", "Şirketler", "Vatandaşlar"]'::jsonb, 1, 5),
  ('2886-kanun-06', '2886-kanun', 'Kesin teminat oranı genel olarak ihale bedelinin yüzde kaçıdır?', '["%6", "%1", "%15", "%20"]'::jsonb, 0, 6),
  ('2886-kanun-07', '2886-kanun', 'İhale kararının onaylanması kaç iş günü içinde yapılmalıdır?', '["15 iş günü", "5 iş günü", "30 iş günü", "3 iş günü"]'::jsonb, 0, 7),
  ('2886-kanun-08', '2886-kanun', 'Kanun kapsamında ''açık eksiltme'' hangi tür ihalelerde kullanılabilir?', '["Kanunda belirtilen tür ihalelerde teklif usulü olarak", "Sadece kira ihalelerinde", "Sadece satış ihalelerinde", "Kullanılmaz"]'::jsonb, 0, 8),
  ('4734-kanun-01', '4734-kanun', '4734 sayılı Kanun''un temel amacı nedir?', '["Kamu hukukuna tabi idarelerin mal/hizmet alımı ve yapım ihalelerinde uygulanacak esasları düzenlemek", "Sadece taşınmaz satışını düzenlemek", "Sadece personel atamasını düzenlemek", "Sadece vergi mevzuatını düzenlemek"]'::jsonb, 0, 1),
  ('4734-kanun-02', '4734-kanun', 'Kanun''a göre temel ihale usulleri nelerdir?', '["Açık ihale usulü ve belli istekliler arasında ihale usulü (esas usuller)", "Sadece pazarlık usulü", "Sadece doğrudan temin", "Sadece kapalı zarf usulü"]'::jsonb, 0, 2),
  ('4734-kanun-03', '4734-kanun', 'Kamu İhale Kurumu''nun temel görevi nedir?', '["İhale mevzuatının uygulanmasını izlemek ve itirazen şikâyetleri incelemek", "Sadece bütçe onaylamak", "Sadece personel atamak", "Sadece vergi toplamak"]'::jsonb, 0, 3),
  ('4734-kanun-04', '4734-kanun', 'İhalelerde temel ilkelerden biri değildir?', '["Saydamlık", "Rekabet", "Güvenirlik", "Kayırmacılık"]'::jsonb, 3, 4),
  ('4734-kanun-05', '4734-kanun', 'Yaklaşık maliyet neyi ifade eder?', '["İdarece gerçekleştirilecek alımın tahmini bedelini", "Kesin ihale bedelini", "Teminat tutarını", "Ceza miktarını"]'::jsonb, 0, 5),
  ('4734-kanun-06', '4734-kanun', 'Doğrudan temin usulü ne zaman kullanılabilir?', '["Kanunda sayılan istisnai ve acil hallerde", "Her zaman serbestçe", "Sadece büyük alımlarda", "Kullanılamaz"]'::jsonb, 0, 6),
  ('4734-kanun-07', '4734-kanun', 'İhalelere katılamayacak olanlar arasında hangisi sayılır?', '["İhaleyi yapan idarede görevli kişiler ile bunların yakınları (kanunda sayılanlar)", "Tüm gerçek kişiler", "Tüm tüzel kişiler", "Yabancı firmalar"]'::jsonb, 0, 7),
  ('4734-kanun-08', '4734-kanun', 'Şikâyet başvurusu hangi süre içinde yapılmalıdır?', '["Kanunda belirtilen süreler içinde (ihale sürecine göre değişir)", "Süre sınırı yoktur", "1 yıl içinde", "6 ay içinde"]'::jsonb, 0, 8),
  ('4735-kanun-01', '4735-kanun', '4735 sayılı Kanun neyi düzenler?', '["4734 sayılı Kanun''a göre yapılan ihaleler sonucu düzenlenen sözleşmelerin uygulanmasını", "Sadece ihale sürecini", "Sadece teminat oranlarını", "Sadece cezaları"]'::jsonb, 0, 1),
  ('4735-kanun-02', '4735-kanun', 'Sözleşmelerde ''süre uzatımı'' hangi hallerde verilebilir?', '["Kanunda sayılan mücbir sebep ve idareden kaynaklanan nedenlerle", "Her istekte", "Hiçbir zaman", "Sadece yüklenici isterse"]'::jsonb, 0, 2),
  ('4735-kanun-03', '4735-kanun', 'Sözleşmenin devri kural olarak nasıldır?', '["İdarenin yazılı izni ile ve kanunda belirtilen şartlarla mümkündür", "Serbestçe yapılabilir", "Hiçbir şekilde yapılamaz", "Sadece idare devredebilir"]'::jsonb, 0, 3),
  ('4735-kanun-04', '4735-kanun', 'Kesin teminat sözleşme bedeli üzerinden genel olarak ne kadardır?', '["%6", "%1", "%10", "%20"]'::jsonb, 0, 4),
  ('4735-kanun-05', '4735-kanun', 'Sözleşmenin feshi hangi hallerde söz konusu olabilir?', '["Yüklenicinin taahhüdünü ihlali gibi kanunda sayılan hallerde", "Sadece idarenin keyfi kararıyla", "Sadece yüklenicinin isteğiyle", "Hiçbir zaman"]'::jsonb, 0, 5),
  ('4735-kanun-06', '4735-kanun', 'Kabul işlemleri neyi ifade eder?', '["Yapım/mal/hizmetin sözleşmeye uygunluğunun idarece tespit edilmesini", "Sadece ödemenin yapılmasını", "Sadece ihalenin sonuçlanmasını", "Sadece teminatın iadesini"]'::jsonb, 0, 6),
  ('4735-kanun-07', '4735-kanun', 'Gecikme cezası ne zaman uygulanır?', '["Yüklenicinin işi süresinde tamamlamaması halinde", "Her durumda", "Sadece idare isterse", "Hiçbir zaman"]'::jsonb, 0, 7),
  ('4735-kanun-08', '4735-kanun', 'Fiyat farkı ödenmesi hangi hallerde söz konusu olabilir?', '["Sözleşmede veya mevzuatta öngörülen şartlarda", "Her zaman serbestçe", "Hiçbir zaman", "Sadece yüklenici talep ederse otomatik"]'::jsonb, 0, 8),
  ('4688-kanun-01', '4688-kanun', '4688 sayılı Kanun temel olarak neyi düzenler?', '["Kamu görevlilerinin sendika kurma ve toplu sözleşme haklarını", "Sadece işçi sendikalarını", "Sadece grev hakkını", "Sadece maaş zamlarını"]'::jsonb, 0, 1),
  ('4688-kanun-02', '4688-kanun', 'Kamu görevlileri hangi amaçla sendika kurabilir?', '["Üyelerinin ekonomik, sosyal ve mesleki hak/menfaatlerini korumak ve geliştirmek", "Sadece siyasi faaliyet yürütmek", "Sadece ticari faaliyet yürütmek", "Sadece burs dağıtmak"]'::jsonb, 0, 2),
  ('4688-kanun-03', '4688-kanun', 'Toplu sözleşme görüşmeleri sonucunda uyuşmazlık halinde başvurulan kurul hangisidir?', '["Kamu Görevlileri Hakem Kurulu", "Yargıtay", "Danıştay", "Sayıştay"]'::jsonb, 0, 3),
  ('4688-kanun-04', '4688-kanun', 'Sendika üyeliği kamu görevlisi için nasıldır?', '["İsteğe bağlıdır", "Zorunludur", "Yasaktır", "Sadece yöneticiler için serbesttir"]'::jsonb, 0, 4),
  ('4688-kanun-05', '4688-kanun', 'Kanun''a göre sendikaların en üst çatı kuruluşu nasıl adlandırılır?', '["Konfederasyon", "Federasyon", "Birlik", "Vakıf"]'::jsonb, 0, 5),
  ('652-khk-01', '652-khk', '652 sayılı KHK tarihsel olarak neyi düzenlemek üzere çıkarılmıştır?', '["Millî Eğitim Bakanlığının teşkilat ve görevlerini", "Sadece öğretmen maaşlarını", "Sadece sınav sistemini", "Sadece ders kitaplarını"]'::jsonb, 0, 1),
  ('652-khk-02', '652-khk', '652 sayılı KHK sonrasında MEB teşkilat yapısı hangi düzenlemeyle güncellenmiştir?', '["1 Sayılı Cumhurbaşkanlığı Kararnamesi ile", "Sadece yönetmeliklerle", "Sadece genelgelerle", "Değişmemiştir"]'::jsonb, 0, 2),
  ('652-khk-03', '652-khk', '652 sayılı KHK''nın kapsamına giren temel konu hangisidir?', '["Bakanlığın merkez ve taşra teşkilatının görev, yetki ve sorumlulukları", "Sadece bütçe kalemleri", "Sadece disiplin cezaları", "Sadece sendikal haklar"]'::jsonb, 0, 3),
  ('bagli-mevzuat-memur-01', 'bagli-mevzuat-memur', 'MEB Personelinin Görevde Yükselme ve Unvan Değişikliği Yönetmeliği''nin temel amacı nedir?', '["Liyakat ve kariyer ilkeleri çerçevesinde atama usul/esaslarını belirlemek", "Sadece maaş zammını düzenlemek", "Sadece izin sürelerini belirlemek", "Sadece disiplin cezalarını belirlemek"]'::jsonb, 0, 1),
  ('bagli-mevzuat-memur-02', 'bagli-mevzuat-memur', 'Görevde yükselme sınavı hangi yöntemle yapılır?', '["Yazılı sınav (ve gerekirse sözlü sınav) ile", "Sadece kıdeme göre", "Sadece mülakatla", "Kura ile"]'::jsonb, 0, 2),
  ('bagli-mevzuat-memur-03', 'bagli-mevzuat-memur', 'Aday memurların yetiştirilmesindeki temel eğitim aşamalarından biri değildir?', '["Temel eğitim", "Hazırlayıcı eğitim", "Staj", "Emeklilik eğitimi"]'::jsonb, 3, 3),
  ('bagli-mevzuat-memur-04', 'bagli-mevzuat-memur', 'Aday memurluk süresi genel olarak ne kadardır?', '["1 yıldan az, 2 yıldan çok olamaz", "Sadece 6 ay", "Sadece 3 yıl", "Süre yoktur"]'::jsonb, 0, 4),
  ('bagli-mevzuat-memur-05', 'bagli-mevzuat-memur', 'Öğretmenlerin Atama ve Yer Değiştirme Yönetmeliği hangi konuyu düzenler?', '["Öğretmenlerin atanma ve yer değiştirme usul/esaslarını", "Sadece maaş bordrosunu", "Sadece izin haklarını", "Sadece emeklilik işlemlerini"]'::jsonb, 0, 5),
  ('bagli-mevzuat-memur-06', 'bagli-mevzuat-memur', 'MEB Personeli İzin Yönergesi''ne göre yıllık izin süresi temel olarak neye göre değişir?', '["Hizmet süresine göre", "Sadece unvana göre", "Sadece cinsiyete göre", "Sadece medeni duruma göre"]'::jsonb, 0, 6),
  ('bagli-mevzuat-memur-07', 'bagli-mevzuat-memur', 'Zorunlu yer değiştirme hangi durumlarda söz konusu olabilir?', '["Hizmet ihtiyacı, sağlık veya kanunda sayılan hallerde", "Hiçbir zaman", "Sadece personelin isteğiyle", "Sadece emeklilikte"]'::jsonb, 0, 7),
  ('bagli-mevzuat-memur-08', 'bagli-mevzuat-memur', 'Görevde yükselme sınavına başvuru şartlarından biri değildir?', '["İlgili unvan için öngörülen hizmet süresini tamamlamış olmak", "Disiplin cezası almamış olmak (kanunda aranan hallerde)", "Gerekli eğitim şartını taşımak", "Sadece nüfusa kayıtlı olmak"]'::jsonb, 3, 8),
  ('bagli-mevzuat-memur-09', 'bagli-mevzuat-memur', 'Aday memur, temel ve hazırlayıcı eğitimlerde başarısız olursa ne olur?', '["Kanunda öngörülen usule göre işlemleri yapılır (gerekirse ilişiği kesilebilir)", "Otomatik olarak asalet tasdik edilir", "Hiçbir işlem yapılmaz", "Doğrudan terfi eder"]'::jsonb, 0, 9),
  ('bagli-mevzuat-memur-10', 'bagli-mevzuat-memur', 'Yer değiştirme suretiyle atamalarda esas alınan ilkelerden biri nedir?', '["Hizmetin gereği ve personelin mazereti gibi hususların birlikte değerlendirilmesi", "Sadece kıdem", "Sadece kura", "Sadece unvan"]'::jsonb, 0, 10),
  ('bagli-mevzuat-sef-01', 'bagli-mevzuat-sef', 'MEB Disiplin Amirleri Yönetmeliği''nin amacı nedir?', '["Disiplin amirlerini ve disiplin cezası vermeye yetkili makamları belirlemek", "Sadece maaşları belirlemek", "Sadece izinleri belirlemek", "Sadece atamaları belirlemek"]'::jsonb, 0, 1),
  ('bagli-mevzuat-sef-02', 'bagli-mevzuat-sef', 'Bir personelin ilk disiplin amiri genel olarak kimdir?', '["Doğrudan bağlı olduğu birim amiri", "Bakan", "Vali", "Cumhurbaşkanı"]'::jsonb, 0, 2),
  ('bagli-mevzuat-sef-03', 'bagli-mevzuat-sef', 'MEB Merkez Teşkilatı İmza Yetkileri Yönergesi neyi düzenler?', '["Bakanlık makamınca hangi yazıların hangi düzeyde imzalanacağını", "Sadece bütçe onaylarını", "Sadece atama kararlarını", "Sadece izin onaylarını"]'::jsonb, 0, 3),
  ('bagli-mevzuat-sef-04', 'bagli-mevzuat-sef', 'Şef kadrosuna görevde yükselme yoluyla atanabilmek için genel şartlardan biri nedir?', '["Yönetmelikte öngörülen hizmet süresi ve sınav şartlarını taşımak", "Sadece kıdemli olmak", "Sadece lisans mezunu olmak yeterlidir, sınav aranmaz", "Hiçbir şart aranmaz"]'::jsonb, 0, 4),
  ('bagli-mevzuat-sef-05', 'bagli-mevzuat-sef', 'Disiplin cezasına itiraz nereye yapılabilir?', '["Kanunda belirtilen disiplin kuruluna veya idare mahkemesine", "Sadece Cumhurbaşkanlığına", "Sadece Sayıştaya", "İtiraz edilemez"]'::jsonb, 0, 5),
  ('bagli-mevzuat-sef-06', 'bagli-mevzuat-sef', 'Aylıktan kesme cezasını vermeye yetkili disiplin amiri genel olarak kimdir?', '["Yönetmelikte belirlenen disiplin amiri", "Sadece Bakan", "Sadece Vali", "Sadece Cumhurbaşkanı"]'::jsonb, 0, 6),
  ('bagli-mevzuat-sef-07', 'bagli-mevzuat-sef', 'MEB Öğretmenlerin Atama ve Yer Değiştirme Yönetmeliği''nde ''zorunlu hizmet bölgesi'' kavramı neyi ifade eder?', '["Hizmet ihtiyacı nedeniyle öncelikli atama yapılan bölgeleri", "Sadece büyükşehirleri", "Sadece sınır illerini", "Kavram yoktur"]'::jsonb, 0, 7),
  ('bagli-mevzuat-sef-08', 'bagli-mevzuat-sef', 'Aday memurun asaletinin tasdiki için gerekli koşullardan biri nedir?', '["Temel ve hazırlayıcı eğitim ile staj döneminde başarılı olmak", "Sadece bir yıl beklemek", "Sadece emeklilik yaşına gelmek", "Hiçbir koşul yoktur"]'::jsonb, 0, 8),
  ('bagli-mevzuat-sef-09', 'bagli-mevzuat-sef', 'MEB Personeli İzin Yönergesi''ne göre mazeret izni hangi hallerde verilebilir?', '["Yönergede sayılan haklı ve mazur sebeplerle", "Hiçbir zaman", "Sadece hastalıkta", "Sadece doğumda"]'::jsonb, 0, 9),
  ('bagli-mevzuat-sef-10', 'bagli-mevzuat-sef', 'Disiplin soruşturmasında savunma hakkı ile ilgili temel ilke nedir?', '["İlgiliye savunmasını yapabilmesi için süre verilmesi zorunludur", "Savunma alınmadan da ceza verilebilir", "Savunma sadece yazılı olmalıdır", "Savunma hakkı yoktur"]'::jsonb, 0, 10),
  ('bagli-mevzuat-sef-11', 'bagli-mevzuat-sef', 'Görevde yükselme eğitimine katılma şartlarından biri nedir?', '["Duyurulan kadro için öngörülen öğrenim ve hizmet süresi şartını taşımak", "Sadece dilekçe vermek yeterlidir", "Sadece kıdem yeterlidir", "Şart aranmaz"]'::jsonb, 0, 11),
  ('bagli-mevzuat-sef-12', 'bagli-mevzuat-sef', 'Şeflik görevinin temel niteliği nedir?', '["Kendisine bağlı birimin iş ve işlemlerini yönetmek/koordine etmek", "Sadece evrak kaydı tutmak", "Sadece temizlik işlerini yönetmek", "Sadece arşiv işleriyle ilgilenmek"]'::jsonb, 0, 12)
on conflict (id) do update set topic_id=excluded.topic_id, prompt=excluded.prompt, options=excluded.options, answer_index=excluded.answer_index, sort_order=excluded.sort_order;

-- ---- exam_kadrolar ----
insert into public.exam_kadrolar (kadro, duration_minutes) values
  ('memur', 75),
  ('sef', 75),
  ('sayman', 75),
  ('sube-mudur', 75)
on conflict (kadro) do update set duration_minutes=excluded.duration_minutes;

-- ---- exam_blueprint_items ----
insert into public.exam_blueprint_items (kadro, topic_id, question_count, sort_order) values
  ('memur', 'turkce', 6, 1),
  ('memur', 'insan-haklari', 2, 2),
  ('memur', 'idare-sistemi', 2, 3),
  ('memur', 'protokol', 2, 4),
  ('memur', 'ataturk', 4, 5),
  ('memur', 'genel-kultur-diger', 5, 6),
  ('memur', 'anayasa', 6, 7),
  ('memur', '657-kanun', 6, 8),
  ('memur', '1739-kanun', 6, 9),
  ('memur', '222-kanun', 4, 10),
  ('memur', '652-khk', 1, 11),
  ('memur', '4982-kanun', 3, 12),
  ('memur', '5442-kanun', 3, 13),
  ('memur', 'bagli-mevzuat-memur', 10, 14),
  ('sef', 'turkce', 6, 1),
  ('sef', 'yonetim-insan-iliskileri', 2, 2),
  ('sef', 'yonetim-liderlik', 3, 3),
  ('sef', 'insan-haklari', 1, 4),
  ('sef', 'yonetimde-etik', 1, 5),
  ('sef', 'idare-sistemi', 2, 6),
  ('sef', 'protokol', 1, 7),
  ('sef', 'ataturk', 2, 8),
  ('sef', 'genel-kultur-diger', 5, 9),
  ('sef', 'anayasa', 6, 10),
  ('sef', '657-kanun', 5, 11),
  ('sef', '1739-kanun', 4, 12),
  ('sef', '222-kanun', 4, 13),
  ('sef', '652-khk', 1, 14),
  ('sef', '4982-kanun', 2, 15),
  ('sef', '5442-kanun', 3, 16),
  ('sef', 'bagli-mevzuat-sef', 12, 17),
  ('sayman', 'turkce', 5, 1),
  ('sayman', 'yonetim-insan-iliskileri', 1, 2),
  ('sayman', 'yonetim-liderlik', 1, 3),
  ('sayman', 'insan-haklari', 1, 4),
  ('sayman', 'yonetimde-etik', 1, 5),
  ('sayman', 'idare-sistemi', 1, 6),
  ('sayman', 'protokol', 1, 7),
  ('sayman', 'ataturk', 2, 8),
  ('sayman', 'genel-kultur-diger', 4, 9),
  ('sayman', 'anayasa', 3, 10),
  ('sayman', '657-kanun', 2, 11),
  ('sayman', '1739-kanun', 2, 12),
  ('sayman', '222-kanun', 2, 13),
  ('sayman', '652-khk', 1, 14),
  ('sayman', '4483-kanun', 2, 15),
  ('sayman', '5018-kanun', 7, 16),
  ('sayman', '2886-kanun', 6, 17),
  ('sayman', '4734-kanun', 6, 18),
  ('sayman', '4735-kanun', 6, 19),
  ('sayman', '4982-kanun', 1, 20),
  ('sayman', '5442-kanun', 1, 21),
  ('sayman', '4688-kanun', 2, 22),
  ('sayman', '5580-kanun', 2, 23),
  ('sube-mudur', 'turkce', 5, 1),
  ('sube-mudur', 'yonetim-insan-iliskileri', 2, 2),
  ('sube-mudur', 'yonetim-liderlik', 3, 3),
  ('sube-mudur', 'insan-haklari', 1, 4),
  ('sube-mudur', 'yonetimde-etik', 1, 5),
  ('sube-mudur', 'idare-sistemi', 2, 6),
  ('sube-mudur', 'protokol', 1, 7),
  ('sube-mudur', 'ataturk', 2, 8),
  ('sube-mudur', 'genel-kultur-diger', 5, 9),
  ('sube-mudur', 'anayasa', 5, 10),
  ('sube-mudur', '657-kanun', 4, 11),
  ('sube-mudur', '1739-kanun', 4, 12),
  ('sube-mudur', '222-kanun', 4, 13),
  ('sube-mudur', '652-khk', 1, 14),
  ('sube-mudur', '4483-kanun', 2, 15),
  ('sube-mudur', '5018-kanun', 3, 16),
  ('sube-mudur', '2886-kanun', 2, 17),
  ('sube-mudur', '4734-kanun', 2, 18),
  ('sube-mudur', '4735-kanun', 1, 19),
  ('sube-mudur', '4982-kanun', 1, 20),
  ('sube-mudur', '5442-kanun', 3, 21),
  ('sube-mudur', '4688-kanun', 3, 22),
  ('sube-mudur', '5580-kanun', 3, 23)
on conflict (kadro, topic_id) do update set question_count=excluded.question_count, sort_order=excluded.sort_order;

commit;
